return {
forceFeedback = {
	invertX		= false,
	invertY		= false,
	shake		= 0.5,
	swapAxes	= false,
	trimmer		= 1,
},
keyCommands = {
{down = iCommandPlaneFlaps,	up = iCommandPlaneFlaps,	value_down = 1,	value_up = 2,	name = _('Alternate Flaps Flight/Takeoff Position'),  category = _('Systems')},
{down = iCommandPlaneFlaps,	up = iCommandPlaneFlaps,	value_down = 3,	value_up = 2,	name = _('Alternate Flaps Landing Position'), category = _('Systems')},
{down = iCommandPlane_SpotSelect_switch, up = iCommandPlane_SpotSelect_switch, value_down = 1,	value_up = 0,	name = _('Alternate Landing Light'),  category = _('Systems')},
{down = iCommandPlane_SpotSelect_switch, up = iCommandPlane_SpotSelect_switch,	value_down = -1,	value_up = 0,	name = _('Alternate Taxi Light Position'), category = _('Systems')},

{down = iCommandMissionRestart,  name = _("Restart Mission"),  category = _("Debug"), },
{down = iCommandViewTower,  name = _("F3 Fly-By view"),  category = _("View"), },
{down = 3022, up = 3022, cockpit_device_id = 33, value_down = -1, value_up = 0,  name = _("RSBN-5 Azimuth Initial Setting Switch - DECREASE"),  category = _("RSBN-5 Control Panel"), },
{down = 3025, cockpit_device_id = 39, value_down = 0,  name = _("Parking Brake Off"),  category = _("Systems"), },
{pressed = iCommandViewForwardSlow, up = iCommandViewForwardSlowStop,  name = _("Zoom in slow"),  category = _("View"), },
{down = 3032, up = 3032, cockpit_device_id = 20, value_down = 1, value_up = 0,  name = _("Warning Lights Test Button"),  category = _("Systems"), },
{down = 3125, cockpit_device_id = 4, value_down = 0,  name = _("C/B Pump Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = iCommandViewCameraUpRight, up = iCommandViewCameraCenter,  name = _("Glance up-right"),  category = _("View Cockpit"), },
{down = 3010, cockpit_device_id = 6, value_down = -1,  name = _("RT-12 JPT Regulator Test Switch, I"),  category = _("Engine Control Panel"), },
{down = iCommandCanopyJettison, up = iCommandCanopyJettison, value_down = 1, value_up = 0,  name = _("Emergency Canopy Jettison Handle"),  category = _("Systems"), },
{down = 3019, cockpit_device_id = 33, value_down = 1,  name = _("RSBN-5 Landing Channel - INCREASE"),  category = _("RSBN-5 Control Panel"), },
{down = iCommandPlaneFlaps, up = iCommandPlaneFlaps, value_down = 1, value_up = 4,  name = _("Flaps Flight Position"),  category = _("Flight Control"), },
{down = iCommandViewMe,  name = _("F2 View own aircraft"),  category = _("View"), },
{down = 3027, cockpit_device_id = 20, value_down = 1,  name = _("Cockpit Lights Switch - RED"),  category = _("Systems"), },
{down = 3024, up = 3024, cockpit_device_id = 33, value_down = 1, value_up = 0,  name = _("RSBN-5 Listen Callsign Button"),  category = _("RSBN-5 Control Panel"), },
{down = iCommandViewEnemies,  name = _("View enemies mode"),  category = _("View Extended"), },
{down = 3102, cockpit_device_id = 4, value_down = 0,  name = _("C/B RSBN Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{down = 3256, cockpit_device_id = 0, value_down = 1,  name = _("Flashlight"),  category = _("View Cockpit"), },
{down = 3010, cockpit_device_id = 37, value_down = 1,  name = _("Emergency Hydraulic Systems Interconnect Lever - OPEN"),  category = _("Systems"), },
{down = iCommandMechClock_LeftLever_Up,  name = _("AChS-1 Cockpit Chronograph Left Knob, Pull"),  category = _("Instrument Panel"), },
{down = iCommandViewNavy,  name = _("F9 Ship view"),  category = _("View"), },
{down = 3078, cockpit_device_id = 4, value_down = 0,  name = _("Turbo Stop Switch"),  category = _("Engine Control Panel"), },
{pressed = 3020, cockpit_device_id = 33, value_pressed = 0.5,  name = _("RSBN-5 Volume Rheostat - CW"),  category = _("RSBN-5 Control Panel"), },
{down = iCommandViewTerrainLock,  name = _("Lock terrain view"),  category = _("View Padlock"), },
{down = iCommandMarkerStatePlane,  name = _("Aircraft Labels"),  category = _("Labels"), },
{down = iCommandViewCameraUpRightSlow,  name = _("Camera snap view up-right"),  category = _("View Cockpit"), },
{down = iCommandPlaneUHFStatus,  name = _("Toggle Radio Control Switch"),  category = _("Communications"), },
{down = 3018, cockpit_device_id = 7, value_down = 0.2,  name = _("Suit Ventilation Mode Switch - COOL"),  category = _("Systems"), },
{pressed = iCommandViewRight, up = iCommandViewStop,  name = _("View right"),  category = _("View Cockpit"), },
{down = 3015, cockpit_device_id = 1, value_down = 1,  name = _("ASP-3NMU Gunsight Mode, GYRO/FIXED"),  category = _("ASP-3NMU Gunsight"), },
{down = 3108, cockpit_device_id = 4, value_down = 0,  name = _("C/B Conditioning Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{pressed = iCommandViewRightSlow, up = iCommandViewStopSlow,  name = _("View Right slow"),  category = _("View"), },
{down = 3101, cockpit_device_id = 4, value_down = 0,  name = _("C/B MRP-RV Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{down = 3136, up = 3136, cockpit_device_id = 4, value_down = 1, value_up = 0,  name = _("Left Pitot Heating On Button"),  category = _("Systems"), },
{pressed = 3018, cockpit_device_id = 39, value_pressed = -1,  name = _("Emergency Wheel Brake - Down"),  category = _("Systems"), },
{pressed = 3033, cockpit_device_id = 20, value_pressed = 0.5,  name = _("Warning Lights Brightness Rheostat - CW"),  category = _("Systems"), },
{down = 3012, cockpit_device_id = 37, value_down = 1,  name = _("Emergency Landing Gear Lever - OPEN"),  category = _("Systems"), },
{down = iCommandPlaneShowKneeboard,  name = _("Kneeboard ON/OFF"),  category = _("Kneeboard"), },
{down = 3096, cockpit_device_id = 4, value_down = 0,  name = _("C/B Engine Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{pressed = 3005, cockpit_device_id = 24, value_pressed = -1,  name = _("Artificial Horizon Zero Pitch Trim Knob, CCW"),  category = _("Instrument Panel"), },
{down = 3116, cockpit_device_id = 4, value_down = 0,  name = _("C/B Gears & Balance Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = 3006, cockpit_device_id = 100, value_down = 2,  name = _("Kneeboard Jump To Shortcut  3"),  category = _("Kneeboard"), },
{pressed = 3018, cockpit_device_id = 39, value_pressed = 1,  name = _("Emergency Wheel Brake - Up"),  category = _("Systems"), },
{down = 3009, cockpit_device_id = 7, value_down = 0.1,  name = _("Anti-Icing Mode Switch - AUTOMATIC"),  category = _("Auxiliary Switch Panel"), },
{down = iCommandPlaneUpStart, up = iCommandPlaneUpStop,  name = _("Aircraft Down"),  category = _("Flight Control"), },
{pressed = iCommandViewDownLeftSlow, up = iCommandViewStopSlow,  name = _("View Down Left slow"),  category = _("View"), },
{down = iCommandPlaneIntercomINTPress, up = iCommandPlaneIntercomINTPress, value_down = 1, value_up = 0,  name = _("INT Button On Stick"),  category = _("Communications"), },
{down = iCommandMarkerState,  name = _("All Labels"),  category = _("Labels"), },
{down = iCommandDecelerate,  name = _("Time decelerate"),  category = _("General"), },
{down = 3006, cockpit_device_id = 100, value_down = 7,  name = _("Kneeboard Jump To Shortcut  8"),  category = _("Kneeboard"), },
{down = 3004, cockpit_device_id = 20, value_down = 1,  name = _("Navigation Lights Brightness Switch - 60%"),  category = _("Auxiliary Switch Panel"), },
{down = iCommandPlane_ShowControls,  name = _("Show controls indicator"),  category = _("General"), },
{down = iCommandViewPlus,  name = _("Toggle tracking launched weapon"),  category = _("View Extended"), },
{down = iCommandViewPitCameraMoveCenter,  name = _("Cockpit Camera Move Center"),  category = _("View Cockpit"), },
{down = iCommandViewFastKeyboard,  name = _("Keyboard Rate Fast"),  category = _("View"), },
{combos = {{key = "JOY_BTN21"}, }, down = iCommandRightEngineStart, up = iCommandRightEngineStart, value_down = 1, value_up = 0,  name = _("Engine Start Button"),  category = _("Engine Control Panel"), },
{combos = {{key = "JOY_BTN8"}, }, down = iCommandPlaneAirBrakeOn, value_down = 1,  name = _("Airbrake Switch - OPEN"),  category = _("Flight Control"), },
{down = iCommandViewAir,  name = _("F2 Aircraft view"),  category = _("View"), },
{down = 3027, cockpit_device_id = 20, value_down = -1,  name = _("Cockpit Lights Switch - WHITE"),  category = _("Systems"), },
{down = 3006, cockpit_device_id = 100, value_down = 6,  name = _("Kneeboard Jump To Shortcut  7"),  category = _("Kneeboard"), },
{down = 3070, cockpit_device_id = 4, value_down = 0,  name = _("Battery Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{down = 3006, cockpit_device_id = 100, value_down = 4,  name = _("Kneeboard Jump To Shortcut  5"),  category = _("Kneeboard"), },
{combos = {{key = "JOY_BTN7"}, }, down = iCommandPlaneAirBrakeOff, value_down = 1,  name = _("Airbrake Switch - CLOSE"),  category = _("Flight Control"), },
{down = iCommandViewCameraDown, up = iCommandViewCameraCenter,  name = _("Glance down"),  category = _("View Cockpit"), },
{down = iCommandPlaneWheelBrakeOn, up = iCommandPlaneWheelBrakeOff,  name = _("Wheel Brake On"),  category = _("Systems"), },
{down = iCommandPlaneTrimUp, up = iCommandPlaneTrimStop, value_down = 1, value_up = 0,  name = _("Elevator Trimmer Switch, PUSH(DESCEND)"),  category = _("Flight Control"), },
{down = iCommandBrakeGo,  name = _("Pause"),  category = _("General"), },
{pressed = iCommandViewUpLeftSlow, up = iCommandViewStopSlow,  name = _("View Up Left slow"),  category = _("View"), },
{down = iCommandViewCockpitChangeSeat, value_down = 2,  name = _("Occupy Seat 2"),  category = _("View Cockpit"), },
{pressed = iCommandViewPitCameraMoveDown, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Down"),  category = _("View Cockpit"), },
{down = 3012, cockpit_device_id = 2, value_down = 1,  name = _("Throttle Toggle Position - IDLE/STOP"),  category = _("Flight Control"), },
{down = iCommandPlaneLeftStart, up = iCommandPlaneLeftStop,  name = _("Aircraft Bank Left"),  category = _("Flight Control"), },
{down = iCommandToggleMirrors,  name = _("Toggle Mirrors"),  category = _("View Cockpit"), },
{down = iCommand_FireExting_TestGroups, up = iCommand_FireExting_TestGroups, value_down = -1, value_up = 0,  name = _("Fire Signals Test Switch, II"),  category = _("Engine Control Panel"), },
{down = iCommandPlaneFlaps, up = iCommandPlaneFlaps, value_down = 3, value_up = 6,  name = _("Flaps Landing Position"),  category = _("Flight Control"), },
{down = iCommandPlaneAirBrake, up = iCommandPlaneAirBrake, value_down = 1, value_up = 0,  name = _("Airbrake Button"),  category = _("Flight Control"), },
{down = 3009, cockpit_device_id = 7, value_down = 0,  name = _("Anti-Icing Mode Switch - OFF"),  category = _("Auxiliary Switch Panel"), },
{down = 3118, cockpit_device_id = 4, value_down = 0,  name = _("C/B Signaling Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = iCommandFriendlyChat,  name = _("Multiplayer chat - mode Allies"),  category = _("General"), },
{pressed = iCommandPlaneConsoleLightsDecrease,  name = _("Cockpit Lights Brightness Rheostat - CCW"),  category = _("Systems"), },
{down = iCommand_FireExting_LeftEngineExting, up = iCommand_FireExting_LeftEngineExting, value_down = 1, value_up = 0,  name = _("Fire Extinguish Button"),  category = _("Engine Control Panel"), },
{down = iCommandPilotSeatAdjustmentUp, up = iCommandPilotSeatAdjustmentStop,  name = _("Seat Adjustment Up"),  category = _("Systems"), },
{down = 3002, cockpit_device_id = 100, value_down = 1,  name = _("Kneeboard Previous Page"),  category = _("Kneeboard"), },
{down = 3016, cockpit_device_id = 6, value_down = 0,  name = _("RT-12 JPT Regulator Manual Disable Switch"),  category = _("Engine Control Panel"), },
{down = iCommand_ExplorationStart,  name = _("Enable exploration mode"),  category = _("View Cockpit"), },
{combos = {{key = "JOY_BTN29"}, }, down = iCommandLeftEngineStop, up = iCommandLeftEngineStart,  name = _("Throttle - Idle/Stop"),  category = _("Engine Control Panel"), },
{pressed = 3021, cockpit_device_id = 17, value_pressed = -0.1,  name = _("GMK-1AE GMC Magnetic Declination Knob - CCW"),  category = _("GMK-1AE GMC Control Panel"), },
{down = 3016, cockpit_device_id = 17, value_down = -1,  name = _("GMK-1AE GMC Mode Switch - GC"),  category = _("GMK-1AE GMC Control Panel"), },
{down = 3016, cockpit_device_id = 37, value_down = 1,  name = _("Emergency RAM Air Turbine Lever - OPEN"),  category = _("Systems"), },
{pressed = 3021, cockpit_device_id = 17, value_pressed = 0.1,  name = _("GMK-1AE GMC Magnetic Declination Knob - CW"),  category = _("GMK-1AE GMC Control Panel"), },
{down = 3131, cockpit_device_id = 4, value_down = 0,  name = _("C/B SARPP Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = 3020, up = 3020, cockpit_device_id = 17, value_down = 1, value_up = 0,  name = _("GMK-1AE GMC Synchronization Button"),  category = _("GMK-1AE GMC Control Panel"), },
{pressed = 3005, cockpit_device_id = 24, value_pressed = 1,  name = _("Artificial Horizon Zero Pitch Trim Knob, CW"),  category = _("Instrument Panel"), },
{down = 3018, cockpit_device_id = 33, value_down = 1,  name = _("RSBN-5 Navigation Channel - INCREASE"),  category = _("RSBN-5 Control Panel"), },
{down = 3019, up = 3019, cockpit_device_id = 17, value_down = -1, value_up = 0,  name = _("GMK-1AE GMC Heading Switch - INCREASE"),  category = _("GMK-1AE GMC Control Panel"), },
{down = 3004, cockpit_device_id = 100, value_down = 1,  name = _("Kneeboard Make Shortcut"),  category = _("Kneeboard"), },
{down = iCommandRALT_Test, up = iCommandRALT_Test_up,  name = _("Radar altimeter test button"),  category = _("Instrument Panel"), },
{down = 3018, up = 3018, cockpit_device_id = 17, value_down = -1, value_up = 0,  name = _("GMK-1AE GMC Test Switch - 300/OFF"),  category = _("GMK-1AE GMC Control Panel"), },
{down = 3127, cockpit_device_id = 4, value_down = 0,  name = _("C/B Ignition 2 Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = 3018, up = 3018, cockpit_device_id = 17, value_down = 1, value_up = 0,  name = _("GMK-1AE GMC Test Switch - 0/OFF"),  category = _("GMK-1AE GMC Control Panel"), },
{down = iCommandViewObjectIgnore,  name = _("Object exclude "),  category = _("View Extended"), },
{down = 3009, cockpit_device_id = 17, value_down = 1,  name = _("GMK-1AE GMC Hemisphere Switch - N"),  category = _("GMK-1AE GMC Control Panel"), },
{down = 3002, cockpit_device_id = 43, value_down = 0,  name = _("SDU Switch - ON/OFF"),  category = _("RSBN-5 Control Panel"), },
{down = 3014, cockpit_device_id = 1, value_down = 1,  name = _("ASP-3NMU Gunsight Color Filter, ON/OFF"),  category = _("ASP-3NMU Gunsight"), },
{down = 3010, cockpit_device_id = 37, value_down = 0,  name = _("Emergency Hydraulic Systems Interconnect Lever - CLOSE"),  category = _("Systems"), },
{down = iCommandPlaneDoAndBack,  name = _("Flight - Complete mission and rejoin"),  category = _("Communications"), },
{down = iCommandPlaneTrimCancel,  name = _("Trimmer - Reset Position"),  category = _("Flight Control"), },
{down = 3015, cockpit_device_id = 17, value_down = 0,  name = _("GMK-1AE GMC Mode Switch - MC/GC"),  category = _("GMK-1AE GMC Control Panel"), },
{pressed = 3010, cockpit_device_id = 17, value_pressed = -0.1,  name = _("GMK-1AE GMC Latitude Knob - CCW"),  category = _("GMK-1AE GMC Control Panel"), },
{down = iCommandViewStatic,  name = _("F12 Static object view"),  category = _("View"), },
{pressed = 3010, cockpit_device_id = 17, value_pressed = 0.1,  name = _("GMK-1AE GMC Latitude Knob - CW"),  category = _("GMK-1AE GMC Control Panel"), },
{down = iCommandMechClock_LeftLever_Down, up = iCommandMechClock_LeftLever_Down_up,  name = _("AChS-1 Cockpit Chronograph Left Knob, Push"),  category = _("Instrument Panel"), },
{pressed = 3005, cockpit_device_id = 1, value_pressed = -1,  name = _("ASP-3NMU Gunsight Brightness Knob Decrease"),  category = _("ASP-3NMU Gunsight"), },
{down = iCommandViewSnapView5, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  5"),  category = _("View Cockpit"), },
{down = 3026, cockpit_device_id = 33, value_down = 0,  name = _("RSBN-5 Emergency Landing Mode On Switch - ON/OFF"),  category = _("RSBN-5 Control Panel"), },
{down = iCommandMechClock_RightLever_Rotate_right,  name = _("AChS-1 Cockpit Chronograph Right Knob, Rotate right"),  category = _("Instrument Panel"), },
{pressed = iCommandViewPitCameraMoveForward, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Forward"),  category = _("View Cockpit"), },
{down = ICommandSwitchToCommonDialog,  name = _("Switch to main menu"),  category = _("Communications"), },
{pressed = iCommandViewCenter,  name = _("View Center"),  category = _("View"), },
{down = iCommandScoresWindowToggle,  name = _("Score window"),  category = _("General"), },
{down = iCommandPlaneGearUp,  name = _("Landing Gear Handle, Up"),  category = _("Systems"), },
{pressed = iCommandViewUpRight, up = iCommandViewStop,  name = _("View up right"),  category = _("View Cockpit"), },
{down = 3003, cockpit_device_id = 100, value_down = 1,  name = _("Kneeboard current position mark point"),  category = _("Kneeboard"), },
{pressed = 3025, cockpit_device_id = 33, value_pressed = -0.3,  name = _("RSBN-5 QNH Pressure Knob - CCW"),  category = _("RSBN-5 Control Panel"), },
{pressed = 3025, cockpit_device_id = 33, value_pressed = 0.3,  name = _("RSBN-5 QNH Pressure Knob - CW"),  category = _("RSBN-5 Control Panel"), },
{down = iCommandPlaneFlaps, up = iCommandPlaneFlaps, value_down = 2, value_up = 5,  name = _("Flaps TakeOff Position"),  category = _("Flight Control"), },
{down = 3023, up = 3023, cockpit_device_id = 33, value_down = -1, value_up = 0,  name = _("RSBN-5 Distance Initial Setting Switch - DECREASE"),  category = _("RSBN-5 Control Panel"), },
{down = iCommandPlane_SpotSelect_switch, value_down = -1,  name = _("Spotlight Switch - TAXI"),  category = _("Systems"), },
{down = 3023, up = 3023, cockpit_device_id = 33, value_down = 1, value_up = 0,  name = _("RSBN-5 Distance Initial Setting Switch - INCREASE"),  category = _("RSBN-5 Control Panel"), },
{down = 3107, cockpit_device_id = 4, value_down = 0,  name = _("C/B SDU Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{down = 3130, cockpit_device_id = 4, value_down = 0,  name = _("C/B Emergency Jettison Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = iCommandViewUnlock,  name = _("Unlock view (stop padlock)"),  category = _("View Padlock"), },
{down = iCommandPlaneFire, up = iCommandPlaneFireOff,  name = _("Weapon Fire Button"),  category = _("Stick"), },
{pressed = 3020, cockpit_device_id = 33, value_pressed = -0.5,  name = _("RSBN-5 Volume Rheostat - CCW"),  category = _("RSBN-5 Control Panel"), },
{pressed = 3003, cockpit_device_id = 26, value_pressed = -1,  name = _("Heading Knob, CCW"),  category = _("Instrument Panel"), },
{down = 3019, cockpit_device_id = 33, value_down = -1,  name = _("RSBN-5 Landing Channel - DECREASE"),  category = _("RSBN-5 Control Panel"), },
{pressed = iCommandMechClock_LeftLever_TurnRight,  name = _("AChS-1 Cockpit Chronograph Left Knob, Rotate right"),  category = _("Instrument Panel"), },
{down = 3010, cockpit_device_id = 24, value_down = 0,  name = _("KPP Pitch Failure Switch - ON/OFF"),  category = _("Systems"), },
{pressed = 3017, cockpit_device_id = 1, value_pressed = -0.1,  name = _("ASP-3NMU Gunsight Glass Lower"),  category = _("ASP-3NMU Gunsight"), },
{pressed = iCommandPlaneConsoleLightsIncrease,  name = _("Cockpit Lights Brightness Rheostat - CW"),  category = _("Systems"), },
{down = 3017, cockpit_device_id = 17, value_down = 0,  name = _("GMK-1AE GMC Hemisphere Switch - N/S"),  category = _("GMK-1AE GMC Control Panel"), },
{down = iCommandRightEngineStop, value_down = -1,  name = _("Engine Stop Switch Cover"),  category = _("Engine Control Panel"), },
{pressed = 3017, cockpit_device_id = 33, value_pressed = 0.5,  name = _("RSBN-5 Lighting Rheostat - CW"),  category = _("RSBN-5 Control Panel"), },
{pressed = 3015, cockpit_device_id = 7, value_pressed = 0.5,  name = _("Cabin Heating Rheostat - CW"),  category = _("Auxiliary Switch Panel"), },
{down = iCommandViewCockpitChangeSeat, value_down = 1,  name = _("Occupy Seat 1"),  category = _("View Cockpit"), },
{down = 3003, cockpit_device_id = 20, value_down = 0.5,  name = _("Navigation Lights Mode Switch - OFF"),  category = _("Auxiliary Switch Panel"), },
{down = iCommandViewSnapView4, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  4"),  category = _("View Cockpit"), },
{down = iCommandEngineLaunchMethod, value_down = 1,  name = _("Engine Launch Method Switch Cover"),  category = _("Engine Control Panel"), },
{down = 3095, cockpit_device_id = 4, value_down = 0,  name = _("Emergency Fuel Switch"),  category = _("Engine Control Panel"), },
{pressed = iCommandMechClock_LeftLever_TurnLeft,  name = _("AChS-1 Cockpit Chronograph Left Knob, Rotate left"),  category = _("Instrument Panel"), },
{down = iCommandViewCameraDownRight, up = iCommandViewCameraCenter,  name = _("Glance down-right"),  category = _("View Cockpit"), },
{down = 3015, up = 3015, cockpit_device_id = 33, value_down = 1, value_up = 0,  name = _("RSBN-5 Identification Button"),  category = _("RSBN-5 Control Panel"), },
{down = 3014, cockpit_device_id = 33, value_down = 0.2,  name = _("RSBN-5 Mode Switch - LANDING"),  category = _("RSBN-5 Control Panel"), },
{down = 3139, up = 3139, cockpit_device_id = 4, value_down = 1, value_up = 0,  name = _("Right Pitot Heating Off Button"),  category = _("Systems"), },
{down = 3134, cockpit_device_id = 4, value_down = 0,  name = _("C/B Arms Switch - ON/OFF"),  category = _("Miscellaneous C/B Switch Panel"), },
{pressed = iCommandViewDownSlow, up = iCommandViewStopSlow,  name = _("View Down slow"),  category = _("View"), },
{pressed = iCommandViewDownRight, up = iCommandViewStop,  name = _("View down right"),  category = _("View Cockpit"), },
{down = iCommandViewBriefing,  name = _("View briefing on/off"),  category = _("General"), },
{down = 3126, cockpit_device_id = 4, value_down = 0,  name = _("C/B Ignition 1 Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = 3014, cockpit_device_id = 33, value_down = 0.1,  name = _("RSBN-5 Mode Switch - NAVIGATION"),  category = _("RSBN-5 Control Panel"), },
{pressed = iCommandViewDownLeft, up = iCommandViewStop,  name = _("View down left"),  category = _("View Cockpit"), },
{pressed = 3017, cockpit_device_id = 33, value_pressed = -0.5,  name = _("RSBN-5 Lighting Rheostat - CCW"),  category = _("RSBN-5 Control Panel"), },
{down = iCommandPlaneUHFSquelch,  name = _("Toggle Radio Squelch Switch"),  category = _("Communications"), },
{down = 3011, cockpit_device_id = 2, value_down = -1,  name = _("Hood - ON/OFF"),  category = _("Systems"), },
{down = 3111, cockpit_device_id = 4, value_down = 0,  name = _("C/B Right Pitot Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{pressed = 3015, cockpit_device_id = 7, value_pressed = -0.5,  name = _("Cabin Heating Mode Switch - CCW"),  category = _("Auxiliary Switch Panel"), },
{down = 3004, cockpit_device_id = 7, value_down = 0.05,  name = _("Cabin Heating Mode Switch - OFF"),  category = _("Auxiliary Switch Panel"), },
{down = 3013, cockpit_device_id = 37, value_down = 0,  name = _("Emergency Flaps Lever - OPEN/CLOSE"),  category = _("Systems"), },
{down = 3004, cockpit_device_id = 7, value_down = 0.2,  name = _("Cabin Heating Mode Switch - COOL"),  category = _("Auxiliary Switch Panel"), },
{down = iCommandViewNormalKeyboard,  name = _("Keyboard Rate Normal"),  category = _("View"), },
{down = 3115, cockpit_device_id = 4, value_down = 0,  name = _("C/B Seat & Helmet Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = iCommandPlane_APU_Start, value_down = -1,  name = _("Turbo Start Button Cover"),  category = _("Engine Control Panel"), },
{down = iCommandViewAWACS,  name = _("F10 Theater map view"),  category = _("View"), },
{down = 3009, cockpit_device_id = 7, value_down = 0.2,  name = _("Anti-Icing Mode Switch - MANUAL"),  category = _("Auxiliary Switch Panel"), },
{down = 3003, cockpit_device_id = 20, value_down = 1,  name = _("Navigation Lights Mode Switch - FIXED LIGHTING"),  category = _("Auxiliary Switch Panel"), },
{down = 3016, up = 3016, cockpit_device_id = 33, value_down = 1, value_up = 0,  name = _("RSBN-5 Testing Button"),  category = _("RSBN-5 Control Panel"), },
{pressed = 3002, cockpit_device_id = 9, value_pressed = -1,  name = _("Barometric Pressure QFE Knob, CCW"),  category = _("Instrument Panel"), },
{down = 3003, cockpit_device_id = 20, value_down = 0,  name = _("Navigation Lights Mode Switch - FLICKER"),  category = _("Auxiliary Switch Panel"), },
{down = iCommandViewLock,  name = _("Lock View (cycle padlock)"),  category = _("View Padlock"), },
{down = 3004, cockpit_device_id = 20, value_down = 0.5,  name = _("Navigation Lights Brightness Switch - 30%"),  category = _("Auxiliary Switch Panel"), },
{down = 3004, cockpit_device_id = 20, value_down = 0,  name = _("Navigation Lights Brightness Switch - 100%"),  category = _("Auxiliary Switch Panel"), },
{down = 3140, cockpit_device_id = 4, value_down = 0,  name = _("Emergency Engine Instruments Power Switch - ON/OFF"),  category = _("Auxiliary Switch Panel"), },
{down = 3020, cockpit_device_id = 7, value_down = 0,  name = _("C/B Air Conditioning Shutoff Switch Cover - OPEN/CLOSE"),  category = _("Miscellaneous C/B Switch Panel"), },
{pressed = 3011, cockpit_device_id = 32, value_pressed = 0.5,  name = _("Oxygen Bottles Interconnect Valve - CCW"),  category = _("Oxygen Control Panel"), },
{down = 3106, cockpit_device_id = 4, value_down = 0,  name = _("C/B De-Icing Signal Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{down = 3129, cockpit_device_id = 4, value_down = 0,  name = _("C/B Fire Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{pressed = 3009, cockpit_device_id = 1, value_pressed = 0.5,  name = _("ASP-3NMU Gunsight Target Wingspan Adjustment Dial, Increase"),  category = _("ASP-3NMU Gunsight"), },
{pressed = iCommandViewDownRightSlow, up = iCommandViewStopSlow,  name = _("View Down Right slow"),  category = _("View"), },
{pressed = iCommandPlane_Oxygen_Supply, value_pressed = -0.5,  name = _("Oxygen Supply Valve - CW"),  category = _("Oxygen Control Panel"), },
{pressed = iCommandPlane_Oxygen_Supply, value_pressed = 0.5,  name = _("Oxygen Supply Valve - CCW"),  category = _("Oxygen Control Panel"), },
{down = iCommandPlaneTrimRight, up = iCommandPlaneTrimStop, value_down = 1, value_up = 0,  name = _("Aileron Trimmer Switch, RIGHT"),  category = _("Flight Control"), },
{down = 3018, cockpit_device_id = 7, value_down = 0.1,  name = _("Suit Ventilation Mode Switch - HEAT"),  category = _("Systems"), },
{down = iCommandPlane_Oxygen_100Oxygen,  name = _("Oxygen Diluter Switch - 100%/NORMAL"),  category = _("Oxygen Control Panel"), },
{down = iCommandPlane_Oxygen_Emergency,  name = _("Emergency Oxygen Switch - ON/OFF"),  category = _("Oxygen Control Panel"), },
{down = 3019, cockpit_device_id = 6, value_down = 0,  name = _("EGT Indicator Switch"),  category = _("Engine Control Panel"), },
{down = iCommandViewFree,  name = _("F11 Airport free camera"),  category = _("View"), },
{down = iCommandViewCameraReturn,  name = _("Return Camera"),  category = _("View Cockpit"), },
{down = iCommandAWACSHomeBearing,  name = _("Request AWACS Home Airbase"),  category = _("Communications"), },
{down = iCommandGraphicsFrameRate,  name = _("Frame rate counter - Service info"),  category = _("General"), },
{down = 3019, cockpit_device_id = 7, value_down = 1,  name = _("C/B Air Conditioning Shutoff Switch - CLOSE"),  category = _("Miscellaneous C/B Switch Panel"), },
{pressed = iCommandPlaneIntercomVolumeIncrease,  name = _("Intercom Volume Knob - Increase"),  category = _("Communications"), },
{down = 3019, cockpit_device_id = 7, value_down = 0,  name = _("C/B Air Conditioning Shutoff Switch - OFF"),  category = _("Miscellaneous C/B Switch Panel"), },
{down = iCommandViewGround,  name = _("F7 Ground unit view"),  category = _("View"), },
{down = iCommandViewSnapView6, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  6"),  category = _("View Cockpit"), },
{down = 3019, cockpit_device_id = 7, value_down = -1,  name = _("C/B Air Conditioning Shutoff Switch - OPEN"),  category = _("Miscellaneous C/B Switch Panel"), },
{down = iCommandViewCameraDownSlow,  name = _("Camera snap view down"),  category = _("View Cockpit"), },
{pressed = 3011, cockpit_device_id = 32, value_pressed = -0.5,  name = _("Oxygen Bottles Interconnect Valve - CW"),  category = _("Oxygen Control Panel"), },
{down = iCommandViewTempCockpitOn, up = iCommandViewTempCockpitOff,  name = _("Cockpit panel view in"),  category = _("View Cockpit"), },
{down = 3135, cockpit_device_id = 4, value_down = 0,  name = _("C/B Intercom Ground Switch - ON/OFF"),  category = _("Miscellaneous C/B Switch Panel"), },
{down = 3133, cockpit_device_id = 4, value_down = 0,  name = _("C/B Signal Switch - ON/OFF"),  category = _("Miscellaneous C/B Switch Panel"), },
{down = 3006, cockpit_device_id = 100, value_down = 5,  name = _("Kneeboard Jump To Shortcut  6"),  category = _("Kneeboard"), },
{down = iCommandNoAcceleration,  name = _("Time normal"),  category = _("General"), },
{down = 3022, up = 3022, cockpit_device_id = 33, value_down = 1, value_up = 0,  name = _("RSBN-5 Azimuth Initial Setting Switch - INCREASE"),  category = _("RSBN-5 Control Panel"), },
{down = iCommandViewCameraUp, up = iCommandViewCameraCenter,  name = _("Glance up"),  category = _("View Cockpit"), },
{down = 3105, cockpit_device_id = 4, value_down = 0,  name = _("C/B Wing Tanks Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{pressed = iCommandViewBack, up = iCommandViewBackStop,  name = _("Zoom out"),  category = _("View Cockpit"), },
{down = 3001, cockpit_device_id = 100, value_down = 1,  name = _("Kneeboard Next Page"),  category = _("Kneeboard"), },
{down = 3104, cockpit_device_id = 4, value_down = 0,  name = _("C/B Emergency Connection RSBN Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{down = 3103, cockpit_device_id = 4, value_down = 0,  name = _("C/B Emergency Connection IFF Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{down = iCommandViewSnapView7, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  7"),  category = _("View Cockpit"), },
{down = iCommandViewLocal,  name = _("F2 Toggle local camera control"),  category = _("View"), },
{down = iCommandEngineLaunchMethod, value_down = 0,  name = _("Engine Launch Method Switch, STARTING"),  category = _("Engine Control Panel"), },
{down = 3097, cockpit_device_id = 4, value_down = 0,  name = _("C/B AGD-GMK Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{down = iCommandEngineLaunchMethod, value_down = 0.1,  name = _("Engine Launch Method Switch, PRESERV"),  category = _("Engine Control Panel"), },
{down = 3100, cockpit_device_id = 4, value_down = 0,  name = _("C/B RDO Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{down = iCommandPlaneGearDown,  name = _("Landing Gear Handle, Down"),  category = _("Systems"), },
{down = 3015, cockpit_device_id = 39, value_down = 1,  name = _("Landing Gear Handle, Neutral"),  category = _("Systems"), },
{down = 3128, cockpit_device_id = 4, value_down = 0,  name = _("C/B Engine Instruments Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = iCommandViewAll,  name = _("View all mode"),  category = _("View Extended"), },
{down = iCommandChat,  name = _("Multiplayer chat - mode All"),  category = _("General"), },
{pressed = 3010, cockpit_device_id = 1, value_pressed = -0.7,  name = _("ASP-3NMU Gunsight Target Distance, Decrease"),  category = _("ASP-3NMU Gunsight"), },
{down = 3124, cockpit_device_id = 4, value_down = 0,  name = _("C/B Start Panel Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = iCommandMechClock_RightLever_Down, up = iCommandMechClock_RightLever_Down_up,  name = _("AChS-1 Cockpit Chronograph Right Knob, Push"),  category = _("Instrument Panel"), },
{down = iCommandViewAWACSJump,  name = _("F10 Jump to theater map view over current point"),  category = _("View"), },
{down = iCommandScreenShot,  name = _("Screenshot"),  category = _("General"), },
{down = iCommandThreatMissilePadlock,  name = _("Threat missile padlock"),  category = _("View Padlock"), },
{down = 3014, cockpit_device_id = 37, value_down = 0,  name = _("Emergency Flaps Lever - CLOSE"),  category = _("Systems"), },
{down = 3120, cockpit_device_id = 4, value_down = 0,  name = _("C/B Left Spotlight Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = iCommandViewSnapView9, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  9"),  category = _("View Cockpit"), },
{down = iCommandViewMirage,  name = _("F12 Civil traffic view"),  category = _("View"), },
{down = 3005, cockpit_device_id = 100, value_down = -1,  name = _("Kneeboard Previous Shortcut"),  category = _("Kneeboard"), },
{down = 3119, cockpit_device_id = 4, value_down = 0,  name = _("C/B Navigation Lights Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = 3117, cockpit_device_id = 4, value_down = 0,  name = _("C/B Control Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = 3004, cockpit_device_id = 7, value_down = 0,  name = _("Cabin Heating Mode Switch - AUTOMATIC"),  category = _("Auxiliary Switch Panel"), },
{down = 3114, cockpit_device_id = 4, value_down = 0,  name = _("C/B SRO Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = 3113, cockpit_device_id = 4, value_down = 0,  name = _("C/B Radio Compass Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{pressed = iCommandViewUp, up = iCommandViewStop,  name = _("View up"),  category = _("View Cockpit"), },
{down = 3112, cockpit_device_id = 4, value_down = 0,  name = _("C/B PT-500 Inverter Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = 3110, cockpit_device_id = 4, value_down = 0,  name = _("C/B Left Pitot Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = 3138, up = 3138, cockpit_device_id = 4, value_down = 1, value_up = 0,  name = _("Right Pitot Heating On Button"),  category = _("Systems"), },
{down = 3109, cockpit_device_id = 4, value_down = 0,  name = _("C/B Anti-Ice Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = iCommandViewChaseArcade,  name = _("F4 Arcade Chase view"),  category = _("View"), },
{down = ICommandSwitchDialog,  name = _("Switch dialog"),  category = _("Communications"), },
{pressed = iCommandViewBackSlow, up = iCommandViewBackSlowStop,  name = _("Zoom out slow"),  category = _("View"), },
{pressed = iCommandViewPitCameraMoveBack, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Back"),  category = _("View Cockpit"), },
{down = 3012, cockpit_device_id = 37, value_down = 0,  name = _("Emergency Landing Gear Lever - CLOSE"),  category = _("Systems"), },
{down = iCommandPlane_R_800_Emergency_Radio,  name = _("Toggle Reserve Intercom Switch"),  category = _("Communications"), },
{pressed = iCommandThrottleDecrease, up = iCommandThrottleStop,  name = _("Thrust Smoothly Down"),  category = _("Flight Control"), },
{down = iCommandPlaneShowKneeboard, up = iCommandPlaneShowKneeboard, value_down = 1, value_up = -1,  name = _("Kneeboard glance view"),  category = _("Kneeboard"), },
{down = iCommandViewCameraJiggle,  name = _("Camera jiggle toggle"),  category = _("View Extended"), },
{down = iCommandViewSpeedUp,  name = _("F11 Camera moving forward"),  category = _("View"), },
{down = iCommandPlaneTrimLeft, up = iCommandPlaneTrimStop, value_down = 1, value_up = 0,  name = _("Aileron Trimmer Switch, LEFT"),  category = _("Flight Control"), },
{down = iCommandEnginesStart,  name = _("Auto Start"),  category = _("Cheat"), },
{down = iCommandPlaneRightStart, up = iCommandPlaneRightStop,  name = _("Aircraft Bank Right"),  category = _("Flight Control"), },
{down = iCommandPilotSeatAdjustmentDown, up = iCommandPilotSeatAdjustmentStop,  name = _("Seat Adjustment Down"),  category = _("Systems"), },
{pressed = iCommandPlaneIntercomVolumeDecrease,  name = _("Intercom Volume Knob - Decrease"),  category = _("Communications"), },
{pressed = iCommandPlaneUHFVolumeDec,  name = _("Radio Volume Knob - Decrease"),  category = _("Communications"), },
{down = iCommandPlaneGear,  name = _("Landing Gear Handle, Up/Down"),  category = _("Systems"), },
{pressed = iCommandPlaneUHFVolumeInc,  name = _("Radio Volume Knob - Increase"),  category = _("Communications"), },
{down = iCommandViewSnapView8, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  8"),  category = _("View Cockpit"), },
{down = iCommandPlaneUHFPresetChannelSelectorDec,  name = _("Radio Channel Knob - Previous"),  category = _("Communications"), },
{down = iCommandPlaneUHFPresetChannelSelectorInc,  name = _("Radio Channel Knob - Next"),  category = _("Communications"), },
{down = 3094, cockpit_device_id = 4, value_down = 0,  name = _("Emergency Fuel Switch Cover"),  category = _("Engine Control Panel"), },
{down = 3006, cockpit_device_id = 100, value_down = 1,  name = _("Kneeboard Jump To Shortcut  2"),  category = _("Kneeboard"), },
{down = iCommandPlaneLeftRudderStart, up = iCommandPlaneLeftRudderStop,  name = _("Aircraft Rudder Left"),  category = _("Flight Control"), },
{pressed = iCommandViewPitCameraMoveRight, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Right"),  category = _("View Cockpit"), },
{pressed = iCommandViewExternalZoomIn, up = iCommandViewExternalZoomInStop,  name = _("Zoom external in"),  category = _("View"), },
{down = iCommandViewSlowDown,  name = _("F11 Camera moving backward"),  category = _("View"), },
{down = 3098, cockpit_device_id = 4, value_down = 0,  name = _("C/B 115V Invertor 1 Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{pressed = iCommandViewExternalZoomOut, up = iCommandViewExternalZoomOutStop,  name = _("Zoom external out"),  category = _("View"), },
{down = iCommandViewCameraLeftSlow,  name = _("Camera snap view left"),  category = _("View Cockpit"), },
{down = iCommandRightEngineStop, value_down = 1,  name = _("Engine Stop Switch"),  category = _("Engine Control Panel"), },
{pressed = 3002, cockpit_device_id = 15, value_pressed = -1,  name = _("Variometer Adjusting Knob, CCW"),  category = _("Instrument Panel"), },
{down = 3079, cockpit_device_id = 4, value_down = 0,  name = _("Turbo Stop Switch Cover"),  category = _("Engine Control Panel"), },
{down = iCommandViewSnapView1, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  1"),  category = _("View Cockpit"), },
{down = 3013, cockpit_device_id = 2, value_down = 0,  name = _("Canopy Lock Handle - LOCK/OPEN"),  category = _("Systems"), },
{down = iCommandViewCameraRight, up = iCommandViewCameraCenter,  name = _("Glance right"),  category = _("View Cockpit"), },
{down = iCommandViewCameraRightSlow,  name = _("Camera snap view right"),  category = _("View Cockpit"), },
{down = iCommandActivePauseOnOff,  name = _("Active Pause"),  category = _("Cheat"), },
{down = 3010, cockpit_device_id = 6, value_down = 1,  name = _("RT-12 JPT Regulator Test Switch, II"),  category = _("Engine Control Panel"), },
{down = 3010, cockpit_device_id = 6, value_down = 0,  name = _("RT-12 JPT Regulator Test Switch, OFF"),  category = _("Engine Control Panel"), },
{down = iCommandViewCameraLeft, up = iCommandViewCameraCenter,  name = _("Glance left"),  category = _("View Cockpit"), },
{down = iCommandViewTargetType,  name = _("F8 Player targets/All targets filter"),  category = _("View"), },
{down = iCommandPlaneFormation,  name = _("Toggle Formation"),  category = _("Communications"), },
{down = iCommandViewSaveAngles,  name = _("Save Cockpit Angles"),  category = _("View Cockpit"), },
{pressed = iCommandThrottleIncrease, up = iCommandThrottleStop,  name = _("Thrust Smoothly Up"),  category = _("Flight Control"), },
{down = 3016, cockpit_device_id = 17, value_down = 1,  name = _("GMK-1AE GMC Mode Switch - MC"),  category = _("GMK-1AE GMC Control Panel"), },
{down = iCommandViewKeepTerrain,  name = _("Keep terrain camera altitude"),  category = _("View Extended"), },
{down = iCommandViewCameraUpLeft, up = iCommandViewCameraCenter,  name = _("Glance up-left"),  category = _("View Cockpit"), },
{down = iCommand_FireExting_TestGroups, up = iCommand_FireExting_TestGroups, value_down = 1, value_up = 0,  name = _("Fire Signals Test Switch, I"),  category = _("Engine Control Panel"), },
{down = iCommandViewTransposeModeOn, up = iCommandViewTransposeModeOff,  name = _("Camera transpose mode on/off"),  category = _("View Cockpit"), },
{down = iCommand_FireExting_ExtinguishersCover,  name = _("Fire Extinguish Button Cover"),  category = _("Engine Control Panel"), },
{down = 3019, up = 3019, cockpit_device_id = 17, value_down = 1, value_up = 0,  name = _("GMK-1AE GMC Heading Switch - DECREASE"),  category = _("GMK-1AE GMC Control Panel"), },
{pressed = iCommandRALT_DangerousAltitudeRotaryLeft,  name = _("Radar altimeter dangerous RALT set rotary left"),  category = _("Instrument Panel"), },
{pressed = iCommandRALT_DangerousAltitudeRotaryRight,  name = _("Radar altimeter dangerous RALT set rotary right"),  category = _("Instrument Panel"), },
{down = 3099, cockpit_device_id = 4, value_down = 0,  name = _("C/B 115V Invertor 2 Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{pressed = 3003, cockpit_device_id = 26, value_pressed = 1,  name = _("Heading Knob, CW"),  category = _("Instrument Panel"), },
{down = 3007, cockpit_device_id = 24, value_down = 1,  name = _("Artificial Horizon Cage"),  category = _("Instrument Panel"), },
{pressed = 3002, cockpit_device_id = 9, value_pressed = 1,  name = _("Barometric Pressure QFE Knob, CW"),  category = _("Instrument Panel"), },
{down = iCommandMechClock_RightLever_Rotate_left,  name = _("AChS-1 Cockpit Chronograph Right Knob, Rotate left"),  category = _("Instrument Panel"), },
{down = 3003, up = 3003, cockpit_device_id = 27, value_down = 1, value_up = 0,  name = _("RSBN-5 Course Accordance Button"),  category = _("RSBN-5 Control Panel"), },
{down = iCommandViewLndgOfficer,  name = _("F9 Landing signal officer view"),  category = _("View"), },
{down = 3018, cockpit_device_id = 33, value_down = -1,  name = _("RSBN-5 Navigation Channel - DECREASE"),  category = _("RSBN-5 Control Panel"), },
{down = iCommandPlaneDownStart, up = iCommandPlaneDownStop,  name = _("Aircraft Up"),  category = _("Flight Control"), },
{down = iCommandPlaneJump,  name = _("Jump into selected aircraft"),  category = _("General"), },
{down = iCommandViewSnapView0, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  0"),  category = _("View Cockpit"), },
{down = iCommandPlaneJettisonWeapons, up = iCommandPlaneJettisonWeaponsUp,  name = _("Weapons Jettison"),  category = _("Emergency"), },
{down = 3014, cockpit_device_id = 37, value_down = 1,  name = _("Emergency Flaps Lever - OPEN"),  category = _("Systems"), },
{pressed = 3005, cockpit_device_id = 1, value_pressed = 1,  name = _("ASP-3NMU Gunsight Brightness Knob, Increase"),  category = _("ASP-3NMU Gunsight"), },
{pressed = 3009, cockpit_device_id = 1, value_pressed = -0.5,  name = _("ASP-3NMU Gunsight Target Wingspan Adjustment Dial, Decrease"),  category = _("ASP-3NMU Gunsight"), },
{down = 3013, cockpit_device_id = 1, value_down = 1,  name = _("ASP-3NMU Gunsight Fixed Reticle Mask Lever"),  category = _("ASP-3NMU Gunsight"), },
{down = 3022, cockpit_device_id = 3, value_down = 1,  name = _("Weapon Fire Button Safety"),  category = _("Stick"), },
{down = iCommandPlaneEject,  name = _("Eject (3 times)"),  category = _("Systems"), },
{down = iCommandViewObjectsAll,  name = _("Objects all excluded - include"),  category = _("View Extended"), },
{down = 3004, cockpit_device_id = 23, value_down = 0,  name = _("ADF Failure Switch - ON/OFF"),  category = _("Systems"), },
{down = iCommandRecoverHuman,  name = _("Get new plane - respawn"),  category = _("General"), },
{down = iCommandPlaneIntercomINT, up = iCommandPlaneIntercomINT, value_down = 1, value_up = 0,  name = _("INT Button"),  category = _("Communications"), },
{down = iCommandPlane_EngageGroundTargets,  name = _("Flight - Attack ground targets"),  category = _("Communications"), },
{down = 3004, cockpit_device_id = 26, value_down = 0,  name = _("GMC Failure Switch - ON/OFF"),  category = _("Systems"), },
{down = iCommandViewNormalMouse,  name = _("Mouse Rate Normal"),  category = _("View"), },
{down = 3122, cockpit_device_id = 4, value_down = 0,  name = _("C/B Red Cockpit Lights Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = iCommandViewAngleDefault,  name = _("Zoom normal"),  category = _("View"), },
{down = 3018, cockpit_device_id = 7, value_down = 0,  name = _("Suit Ventilation Mode Switch - AUTO"),  category = _("Systems"), },
{pressed = 3010, cockpit_device_id = 1, value_pressed = 0.7,  name = _("ASP-3NMU Gunsight Target Distance, Increase"),  category = _("ASP-3NMU Gunsight"), },
{pressed = 3017, cockpit_device_id = 7, value_pressed = 0.5,  name = _("Suit Ventilation Air Louvre Rheostat - CW"),  category = _("Systems"), },
{down = 3137, up = 3137, cockpit_device_id = 4, value_down = 1, value_up = 0,  name = _("Left Pitot Heating Off Button"),  category = _("Systems"), },
{down = 3015, cockpit_device_id = 37, value_down = 0,  name = _("Emergency RAM Air Turbine Lever - OPEN/CLOSE"),  category = _("Systems"), },
{down = 3121, cockpit_device_id = 4, value_down = 0,  name = _("C/B Right Spotlight Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = iCommandAllMissilePadlock,  name = _("All missiles padlock"),  category = _("View Padlock"), },
{down = 3009, cockpit_device_id = 37, value_down = 0,  name = _("Emergency Hydraulic Systems Interconnect Lever - OPEN/CLOSE"),  category = _("Systems"), },
{down = 3016, cockpit_device_id = 37, value_down = 0,  name = _("Emergency RAM Air Turbine Lever - CLOSE"),  category = _("Systems"), },
{down = 3132, cockpit_device_id = 4, value_down = 0,  name = _("C/B Seat Switch - ON/OFF"),  category = _("Miscellaneous C/B Switch Panel"), },
{pressed = iCommandViewLeftSlow, up = iCommandViewStopSlow,  name = _("View Left slow"),  category = _("View"), },
{down = iCommandPlaneDoAndHome,  name = _("Flight - Complete mission and RTB"),  category = _("Communications"), },
{down = 3006, cockpit_device_id = 100, value_down = 8,  name = _("Kneeboard Jump To Shortcut  9"),  category = _("Kneeboard"), },
{down = iCommandViewCameraDownLeft, up = iCommandViewCameraCenter,  name = _("Glance down-left"),  category = _("View Cockpit"), },
{down = iCommandPlaneFonar,  name = _("Canopy Open/Close"),  category = _("Systems"), },
{combos = {{key = "JOY_BTN26"}, }, down = iCommandPlane_APU_Start, up = iCommandPlane_APU_Start, value_down = 1, value_up = 0,  name = _("Turbo Start Button"),  category = _("Engine Control Panel"), },
{pressed = iCommandViewLeft, up = iCommandViewStop,  name = _("View left"),  category = _("View Cockpit"), },
{down = 3005, cockpit_device_id = 100, value_down = 1,  name = _("Kneeboard Next Shortcut"),  category = _("Kneeboard"), },
{down = iCommandViewSnapView3, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  3"),  category = _("View Cockpit"), },
{down = iCommandViewTempCockpitToggle,  name = _("Cockpit panel view toggle"),  category = _("View Cockpit"), },
{down = iCommandPlane_R_800_ADF_Sound_switch,  name = _("Toggle Intercom ADF Switch"),  category = _("Communications"), },
{down = iCommandMissionResourcesManagement,  name = _("Rearming and Refueling Window"),  category = _("General"), },
{down = iCommandAllChat,  name = _("Chat read/write All"),  category = _("General"), },
{down = iCommandPlaneAttackMyTarget,  name = _("Attack My Target"),  category = _("Communications"), },
{down = iCommandViewTowerJump,  name = _("F3 Fly-By jump view"),  category = _("View"), },
{down = iCommandViewLocomotivesToggle,  name = _("F12 Trains/cars toggle"),  category = _("View"), },
{down = 3010, up = 3010, cockpit_device_id = 7, value_down = 1, value_up = 0,  name = _("Anti-Ice Test Button"),  category = _("Systems"), },
{down = iCommandAccelerate,  name = _("Time accelerate"),  category = _("General"), },
{pressed = iCommandViewUpSlow, up = iCommandViewStopSlow,  name = _("View Up slow"),  category = _("View"), },
{pressed = 3033, cockpit_device_id = 20, value_pressed = -0.5,  name = _("Warning Lights Brightness Rheostat - CCW"),  category = _("Systems"), },
{down = 3015, cockpit_device_id = 6, value_down = 0,  name = _("RT-12 JPT Regulator Manual Disable Switch Cover"),  category = _("Engine Control Panel"), },
{down = 3014, cockpit_device_id = 33, value_down = 0,  name = _("RSBN-5 Mode Switch - GLIDE PATH"),  category = _("RSBN-5 Control Panel"), },
{down = iCommandQuit,  name = _("End mission"),  category = _("General"), },
{down = 3017, cockpit_device_id = 6, value_down = 0,  name = _("RT-12 JPT Regulator Power Switch"),  category = _("Engine Control Panel"), },
{down = iCommandPlaneCoverMySix,  name = _("Cover me"),  category = _("Communications"), },
{down = iCommandViewRear,  name = _("F4 Look back view"),  category = _("View"), },
{combos = {{key = "JOY_BTN5"}, }, down = iCommandPlaneIntercomVHF, up = iCommandPlaneIntercomVHF, value_down = 1, value_up = 0,  name = _("Radio Button"),  category = _("Communications"), },
{down = 3021, up = 3021, cockpit_device_id = 33, value_down = 1, value_up = 0,  name = _("RSBN-5 Azimuth 0 Setting Button"),  category = _("RSBN-5 Control Panel"), },
{pressed = iCommandViewPitCameraMoveUp, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Up"),  category = _("View Cockpit"), },
{down = iCommandViewTargets,  name = _("F8 Target view"),  category = _("View"), },
{down = iCommandViewCameraCenter,  name = _("Center Camera View"),  category = _("View Cockpit"), },
{down = 3011, cockpit_device_id = 37, value_down = 0,  name = _("Emergency Landing Gear Lever - OPEN/CLOSE"),  category = _("Systems"), },
{down = 3027, cockpit_device_id = 20, value_down = 0,  name = _("Cockpit Lights Switch - OFF"),  category = _("Systems"), },
{down = ICommandToggleConsole,  name = _("Toggle Console"),  category = _("Debug"), },
{down = 3006, cockpit_device_id = 100, value_down = 3,  name = _("Kneeboard Jump To Shortcut  4"),  category = _("Kneeboard"), },
{down = iCommandViewFightGround,  name = _("F5 Ground hostile view"),  category = _("View"), },
{down = iCommandPlaneJoinUp,  name = _("Join Up Formation"),  category = _("Communications"), },
{down = iCommandViewCockpit,  name = _("F1 Cockpit view"),  category = _("View"), },
{down = iCommandViewSnapView2, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  2"),  category = _("View Cockpit"), },
{pressed = iCommandViewDown, up = iCommandViewStop,  name = _("View down"),  category = _("View Cockpit"), },
{down = iCommandCockpitShowPilotOnOff,  name = _("Show pilot"),  category = _("General"), },
{down = iCommandPlane_SpotSelect_switch, value_down = 1,  name = _("Spotlight Switch - LANDING"),  category = _("Systems"), },
{down = iCommandViewHUDOnlyOnOff,  name = _("F1 HUD only view switch"),  category = _("View"), },
{down = 3073, cockpit_device_id = 4, value_down = 0,  name = _("Net Switch - ON/OFF"),  category = _("Miscellaneous C/B Switch Panel"), },
{pressed = iCommandViewPitCameraMoveLeft, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Left"),  category = _("View Cockpit"), },
{down = iCommandViewWeapons,  name = _("F6 Released weapon view"),  category = _("View"), },
{down = iCommandPlane_SpotSelect_switch, value_down = 0,  name = _("Spotlight Switch - OFF"),  category = _("Systems"), },
{down = iCommandViewWeaponAndTarget,  name = _("F6 Weapon to target view"),  category = _("View"), },
{down = 3071, cockpit_device_id = 4, value_down = 0,  name = _("Main Generator Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{down = iCommandViewCameraDownLeftSlow,  name = _("Camera snap view down-left"),  category = _("View Cockpit"), },
{down = iCommandViewCoordinatesInLinearUnits,  name = _("Info bar coordinate units toggle"),  category = _("General"), },
{down = 3020, cockpit_device_id = 20, value_down = 1,  name = _("Emergency Cockpit Light Switch"),  category = _("Systems"), },
{down = iCommandPlaneAUTIncreaseRegime,  name = _("Thrust Step Up"),  category = _("Flight Control"), },
{down = iCommandLeftEngineStop,  name = _("Throttle - STOP"),  category = _("Flight Control"), },
{down = iCommandLeftEngineStart,  name = _("Throttle - IDLE"),  category = _("Flight Control"), },
{down = iCommandPlaneAUTDecreaseRegime,  name = _("Thrust Step Down"),  category = _("Flight Control"), },
{down = 3006, cockpit_device_id = 100, value_down = 9,  name = _("Kneeboard Jump To Shortcut 10"),  category = _("Kneeboard"), },
{down = iCommandPlaneTrimDown, up = iCommandPlaneTrimStop, value_down = 1, value_up = 0,  name = _("Elevator Trimmer Switch, PULL(CLIMB)"),  category = _("Flight Control"), },
{down = iCommandPlaneRightRudderStart, up = iCommandPlaneRightRudderStop,  name = _("Aircraft Rudder Right"),  category = _("Flight Control"), },
{down = iCommandViewCameraUpSlow,  name = _("Camera snap view up"),  category = _("View Cockpit"), },
{down = 3004, cockpit_device_id = 7, value_down = 0.1,  name = _("Cabin Heating Mode Switch - HEAT"),  category = _("Auxiliary Switch Panel"), },
{down = iCommandSoundOnOff,  name = _("Sound On/Off"),  category = _("General"), },
{down = 3011, cockpit_device_id = 24, value_down = 0,  name = _("KPP Bank Failure Switch - ON/OFF"),  category = _("Systems"), },
{down = iCommandEnginesStop,  name = _("Auto Stop"),  category = _("Cheat"), },
{down = iCommandViewCameraUpLeftSlow,  name = _("Camera snap view up-left"),  category = _("View Cockpit"), },
{down = iCommandRightEngineStart, value_down = -1,  name = _("Engine Start Button Cover"),  category = _("Engine Control Panel"), },
{down = 3006, cockpit_device_id = 100, value_down = 0,  name = _("Kneeboard Jump To Shortcut  1"),  category = _("Kneeboard"), },
{down = iCommandMarkerStateRocket,  name = _("Missile Labels"),  category = _("Labels"), },
{down = iCommandMarkerStateShip,  name = _("Vehicle & Ship Labels"),  category = _("Labels"), },
{down = iCommandViewFreeJump,  name = _("F11 Jump to free camera"),  category = _("View"), },
{down = iCommandViewExternalZoomDefault,  name = _("Zoom external normal"),  category = _("View"), },
{down = 3009, cockpit_device_id = 17, value_down = -1,  name = _("GMK-1AE GMC Hemisphere Switch - S"),  category = _("GMK-1AE GMC Control Panel"), },
{down = iCommandLeftEngineFuelValveShutOff,  name = _("Fuel Shut-Off Lever - SHUT/OPEN"),  category = _("Systems"), },
{pressed = 3002, cockpit_device_id = 15, value_pressed = 1,  name = _("Variometer Adjusting Knob, CW"),  category = _("Instrument Panel"), },
{down = iCommandViewSwitchReverse,  name = _("Objects switching direction reverse "),  category = _("View Extended"), },
{pressed = 3017, cockpit_device_id = 7, value_pressed = -0.5,  name = _("Suit Ventilation Air Louvre Rheostat - CCW"),  category = _("Systems"), },
{down = iCommandViewSwitchForward,  name = _("Objects switching direction forward "),  category = _("View Extended"), },
{down = iCommandViewFriends,  name = _("View friends mode"),  category = _("View Extended"), },
{down = iCommandInfoOnOff,  name = _("Info bar view toggle"),  category = _("General"), },
{down = iCommand_ENG_INTERF_EngVibrDetectorBIT, up = iCommand_ENG_INTERF_EngVibrDetectorBIT, value_down = 1, value_up = 0,  name = _("IV-300 Engine Vibration Test Button"),  category = _("Engine Control Panel"), },
{pressed = iCommandViewForward, up = iCommandViewForwardStop,  name = _("Zoom in"),  category = _("View Cockpit"), },
{down = iCommandViewPitHeadOnOff,  name = _("F1 Head shift movement on / off"),  category = _("View"), },
{down = iCommandPlane_EngageAirDefenses,  name = _("Flight - Attack air defenses"),  category = _("Communications"), },
{down = 3072, cockpit_device_id = 4, value_down = 0,  name = _("Emergency Generator Switch - ON/OFF"),  category = _("Main C/B Switch Panel"), },
{down = iCommandViewSlowKeyboard,  name = _("Keyboard Rate Slow"),  category = _("View"), },
{down = iCommandViewCameraBaseReturn,  name = _("Return Camera Base"),  category = _("View Cockpit"), },
{down = iCommandViewFromTo,  name = _("F2 Toggle camera position"),  category = _("View"), },
{down = iCommandCockpitClickModeOnOff,  name = _("Clickable mouse cockpit mode On/Off"),  category = _("General"), },
{down = iCommandViewCameraDownRightSlow,  name = _("Camera snap view down-right"),  category = _("View Cockpit"), },
{down = iCommandViewPanToggle,  name = _("Camera pan mode toggle"),  category = _("View Cockpit"), },
{down = iCommandEngineLaunchMethod, value_down = 0.2,  name = _("Engine Launch Method Switch, COLD ROTATION"),  category = _("Engine Control Panel"), },
{pressed = iCommandViewUpLeft, up = iCommandViewStop,  name = _("View up left"),  category = _("View Cockpit"), },
{pressed = 3017, cockpit_device_id = 1, value_pressed = 0.1,  name = _("ASP-3NMU Gunsight Glass Raise"),  category = _("ASP-3NMU Gunsight"), },
{down = iCommandToggleCommandMenu,  name = _("Communication menu"),  category = _("Communications"), },
{down = 3123, cockpit_device_id = 4, value_down = 0,  name = _("C/B White Cockpit Lights Switch - ON/OFF"),  category = _("Aft C/B Switch Panel"), },
{down = iCommandViewFight,  name = _("F5 nearest AC view"),  category = _("View"), },
{down = iCommandViewSlowMouse,  name = _("Mouse Rate Slow"),  category = _("View"), },
{down = iCommandViewFastMouse,  name = _("Mouse Rate Fast"),  category = _("View"), },
{down = iCommandViewChase,  name = _("F4 Chase view"),  category = _("View"), },
{down = iCommandNaturalViewCockpitIn,  name = _("F1 Natural head movement view"),  category = _("View"), },
{pressed = iCommandViewUpRightSlow, up = iCommandViewStopSlow,  name = _("View Up Right slow"),  category = _("View"), },
},
axisCommands = {
{action = iCommandViewLongitudeTransAbs,  name = _("Absolute Longitude Shift Camera View"), },
{action = iCommandViewHorizontalAbs,  name = _("Absolute Camera Horizontal View"), },
{action = 3007, cockpit_device_id = 1,  name = _("ASP-3NMU Gunsight Target Wingspan Adjustment Dial"), },
{action = 3020, cockpit_device_id = 39,  name = _("Second Cockpit Emergency Wheel Brake Lever"), },
{combos = {{key = "JOY_Z"}, }, action = iCommandPlaneThrustCommon,  name = _("Thrust"), },
{action = 3019, cockpit_device_id = 39,  name = _("Front Cockpit Emergency Wheel Brake Lever"), },
{action = iCommandViewZoomAbs,  name = _("Zoom View"), },
{action = iCommandPlaneRoll,  name = _("Roll"), },
{action = iCommandViewVerticalAbs,  name = _("Absolute Camera Vertical View"), },
{action = 3006, cockpit_device_id = 1,  name = _("ASP-3NMU Gunsight Target Distance"), },
{action = iCommandPlanePitch,  name = _("Pitch"), },
{action = iCommandPlaneZoomView,  name = _("Camera Zoom View"), },
{action = iCommandPlaneViewVertical,  name = _("Camera Vertical View"), },
{action = iCommandPlaneViewHorizontal,  name = _("Camera Horizontal View"), },
{action = 3018, cockpit_device_id = 1,  name = _("ASP-3 Glass Raise/Lower"), },
{action = iCommandPlaneRudder,  name = _("Rudder"), },
{action = iCommandWheelBrake,  name = _("Wheel Brake"), },
{action = iCommandViewVertTransAbs,  name = _("Absolute Vertical Shift Camera View"), },
{action = iCommandViewHorTransAbs,  name = _("Absolute Horizontal Shift Camera View"), },
{action = iCommandViewRollAbs,  name = _("Absolute Roll Shift Camera View"), },
},
}