return {
forceFeedback = {
	invertX		= false,
	invertY		= false,
	shake		= 0.5,
	swapAxes	= false,
	trimmer		= 1,
},
keyCommands = {

-- Custom
{down = nav_lights_commands.F86_CockpitDeviceCommand_LandAndTaxiLights, up = nav_lights_commands.F86_CockpitDeviceCommand_LandAndTaxiLights, cockpit_device_id = devices.NAV_LIGHTS_INTERFACE, value_down = -1, value_up= 0, name = 'Alternate Landing & Taxi Lights - Retract & Off', category = 'Left Forward Console'},
{down = nav_lights_commands.F86_CockpitDeviceCommand_LandAndTaxiLights, up = nav_lights_commands.F86_CockpitDeviceCommand_LandAndTaxiLights, cockpit_device_id = devices.NAV_LIGHTS_INTERFACE, value_down = 1, value_up= 0, name = 'Alternate Landing & Taxi Lights - Off & On', category = 'Left Forward Console'},

{down = electric_commands.F86_CockpitDeviceCommand_EngineMasterSw_EXT, up = electric_commands.F86_CockpitDeviceCommand_EngineMasterSw_EXT, cockpit_device_id = devices.ELEC_INTERFACE, value_down = 1, value_up = 1, name = 'Alternate Engine Master', category = 'Right Forward Console'},

{down = iCommandPlaneFlapsOn, up = control_commands.F86_CockpitDeviceCommand_FlapsHandle, cockpit_device_id = devices.CONTROL_INTERFACE, value_down = 0, value_up = 0, name = 'Alternate Flaps Down', category = 'Systems'},
{down = iCommandPlaneFlapsOff, up = control_commands.F86_CockpitDeviceCommand_FlapsHandle, cockpit_device_id = devices.CONTROL_INTERFACE, value_down = 0, value_up = 0, name = 'Alternate Flaps Up', category = 'Systems'},

{down = iCommandMissionRestart,  name = _("Restart Mission"),  category = _("Debug"), },
{pressed = 3009, cockpit_device_id = 27, value_pressed = -1,  name = _("AN/ARN-6 East/West Variation Knob - CCW/East"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandPlaneRightRudderStart, up = iCommandPlaneRightRudderStop,  name = _("Aircraft Rudder Right"),  category = _("Flight Control"), },
{down = 3014, cockpit_device_id = 27, value_down = -1,  name = _("AN/ARN-6 Frequency Band Switch - CCW/Decrease"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandViewMe,  name = _("F2 View own aircraft"),  category = _("View"), },
{combos = {{key = "JOY_BTN11"}, }, down = iCommandPlaneDesignate_CageOn, up = iCommandPlaneDesignate_CageOff,  name = _("A-4 Sight Electrical Caging Button (On Throttle)"),  category = _("A-4 Sight"), },
{pressed = 3005, cockpit_device_id = 22, value_pressed = -0.2,  name = _("A-4 Sight Reticle Dimmer Control - CCW/DIM"),  category = _("A-4 Sight"), },
{down = iCommandViewEnemies,  name = _("View enemies mode"),  category = _("View Extended"), },
{down = 3027, cockpit_device_id = 5, value_down = 1,  name = _("Rocket Release Selector Switch - Up"),  category = _("Center Pedestal"), },
{down = iCommandViewNavy,  name = _("F9 Ship view"),  category = _("View"), },
{down = 3029, cockpit_device_id = 5, value_down = 1,  name = _("Variable Sight Selector Unit - Sight Function Selector Lever - CCW"),  category = _("Center Pedestal"), },
{pressed = 3009, cockpit_device_id = 17, value_pressed = -0.5,  name = _("Console and Panel Light Rheostat - CCW/Decrease"),  category = _("Interior Light Control Panel"), },
{down = 3005, up = 3005, cockpit_device_id = 3, value_down = 1, value_up = 0,  name = _("Outboard Drop Tank Empty Indicator Light"),  category = _("Drop Tank Control Panel"), },
{down = iCommandViewTerrainLock,  name = _("Lock terrain view"),  category = _("View Padlock"), },
{down = iCommandMarkerStatePlane,  name = _("Aircraft Labels"),  category = _("Labels"), },
{down = iCommandViewCameraUpRightSlow,  name = _("Camera snap view up-right"),  category = _("View Cockpit"), },
{pressed = iCommandViewRight, up = iCommandViewStop,  name = _("View right"),  category = _("View Cockpit"), },
{pressed = 3035, cockpit_device_id = 5, value_pressed = 1,  name = _("A-4 Sight Bombing Altimeter Target Altitude Knob - CW/Increase"),  category = _("A-4 Sight"), },
{pressed = iCommandViewLeft, up = iCommandViewStop,  name = _("View left"),  category = _("View Cockpit"), },
{pressed = 3002, cockpit_device_id = 21, value_pressed = 1,  name = _("A-4 Sight Radar Range Sweep Rheostat - CW/Increase"),  category = _("A-4 Sight"), },
{down = 3005, cockpit_device_id = 18, value_down = -1,  name = _("Landing & Taxi Lights Switch - Down"),  category = _("Left Forward Console"), },
{down = 3005, cockpit_device_id = 18, value_down = 1,  name = _("Landing & Taxi Lights Switch - Up"),  category = _("Left Forward Console"), },
{pressed = iCommandViewUpSlow, up = iCommandViewStopSlow,  name = _("View Up slow"),  category = _("View"), },
{down = 3007, cockpit_device_id = 29, value_down = 1,  name = _("AN/APX-6 IFF Mode 2 Switch - Up"),  category = _("AN/APX-6 IFF Transponder"), },
{down = iCommandPlaneShowKneeboard,  name = _("Kneeboard ON/OFF"),  category = _("Kneeboard"), },
{down = 3017, cockpit_device_id = 22, value_down = 1,  name = _("A-4 Sight Mechanical Caging Lever"),  category = _("A-4 Sight"), },
{down = 3009, up = 3009, cockpit_device_id = 2, value_down = 1, value_up = 0,  name = _("Landing Gear Warning Horn Cutout Button"),  category = _("Left Forward Console"), },
{down = 3007, cockpit_device_id = 29, value_down = -1,  name = _("AN/APX-6 IFF Mode 2 Switch - Down"),  category = _("AN/APX-6 IFF Transponder"), },
{down = 3015, cockpit_device_id = 27, value_down = 1,  name = _("AN/ARN-6 Scale Light Switch - Up"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandPlaneUpStart, up = iCommandPlaneUpStop,  name = _("Aircraft Down"),  category = _("Flight Control"), },
{pressed = iCommandViewDownLeftSlow, up = iCommandViewStopSlow,  name = _("View Down Left slow"),  category = _("View"), },
{down = 3007, cockpit_device_id = 26, value_down = -1,  name = _("AN/ARC-27 UHF Power Switch - CCW"),  category = _("AN/ARC-27 UHF Radio"), },
{down = iCommandMarkerState,  name = _("All Labels"),  category = _("Labels"), },
{down = iCommandViewTargets,  name = _("F8 Target view"),  category = _("View"), },
{down = iCommandPlane_ShowControls,  name = _("Show controls indicator"),  category = _("General"), },
{down = iCommandViewPitCameraMoveCenter,  name = _("Cockpit Camera Move Center"),  category = _("View Cockpit"), },
{down = iCommandViewFastKeyboard,  name = _("Keyboard Rate Fast"),  category = _("View"), },
{pressed = iCommandPlaneTrimRight, up = iCommandPlaneTrimStop,  name = _("Trim Right"),  category = _("Flight Control"), },
{pressed = 3036, cockpit_device_id = 5, value_pressed = 1,  name = _("A-4 Sight Bombing Altimeter Index Altitude Handle - CW/Increase"),  category = _("A-4 Sight"), },
{down = iCommandViewAir,  name = _("F2 Aircraft view"),  category = _("View"), },
{down = 3031, cockpit_device_id = 5, value_down = -1,  name = _("Rocket Fuze (Arming) Switch"),  category = _("Center Pedestal"), },
{pressed = 3011, cockpit_device_id = 27, value_pressed = 0.3,  name = _("AN/ARN-6 Audio Volume Control - Up"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandViewCameraDown, up = iCommandViewCameraCenter,  name = _("Glance down"),  category = _("View Cockpit"), },
{down = 3025, cockpit_device_id = 5, value_down = -1,  name = _("Gun-Missile Selector Switch - CW"),  category = _("Center Pedestal"), },
{down = 3013, cockpit_device_id = 27, value_down = -1,  name = _("AN/ARN-6 Function Selector Switch - CCW"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandPlaneWheelBrakeOn, up = iCommandPlaneWheelBrakeOff,  name = _("Wheel Brake On"),  category = _("Systems"), },
{down = 3048, cockpit_device_id = 1, value_down = 1,  name = _("Generator Switch - Up"),  category = _("Right Forward Console"), },
{down = 3048, up = 3048, cockpit_device_id = 1, value_down = -1, value_up = 0,  name = _("Generator Switch - Down"),  category = _("Right Forward Console"), },
{down = iCommandBrakeGo,  name = _("Pause"),  category = _("General"), },
{pressed = iCommandViewUpLeftSlow, up = iCommandViewStopSlow,  name = _("View Up Left slow"),  category = _("View"), },
{down = 3001, cockpit_device_id = 13, value_down = 0,  name = _("Flaps Stop"),  category = _("Systems"), },
{pressed = iCommandViewPitCameraMoveDown, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Down"),  category = _("View Cockpit"), },
{down = iCommandViewLeftMirrorOn, up = iCommandViewLeftMirrorOff,  name = _("Mirror Left On"),  category = _("View Cockpit"), },
{down = iCommandToggleMirrors,  name = _("Toggle Mirrors"),  category = _("View Cockpit"), },
{down = 3024, cockpit_device_id = 22, value_down = 1,  name = _("A-4 Sight Filament Selector Switch"),  category = _("Center Pedestal"), },
{down = iCommandFriendlyChat,  name = _("Multiplayer chat - mode Allies"),  category = _("General"), },
{pressed = iCommandPlaneIncreaseBase_Distance, up = iCommandPlaneStopBase_Distance,  name = _("A-4 Sight Wing Span Adjustment Knob - Wing Span Increase"),  category = _("A-4 Sight"), },
{down = 3009, cockpit_device_id = 16, value_down = 1,  name = _("Engine Anti-Ice & Screen Switch - Up"),  category = _("Left Forward Console"), },
{down = 3009, cockpit_device_id = 16, value_down = -1,  name = _("Engine Anti-Ice & Screen Switch - Down"),  category = _("Left Forward Console"), },
{down = 3006, cockpit_device_id = 29, value_down = -1,  name = _("AN/APX-6 IFF Master Switch - CCW"),  category = _("AN/APX-6 IFF Transponder"), },
{down = 3002, cockpit_device_id = 100, value_down = 1,  name = _("Kneeboard Previous Page"),  category = _("Kneeboard"), },
{combos = {{key = "JOY_BTN7"}, }, pressed = iCommandPlaneAirBrakeOff, up = iCommandPlaneAirBrakeOff, value_pressed = 1, value_up = 0,  name = _("Airbrake Off"),  category = _("Systems"), },
{down = iCommandPlaneFlaps,  name = _("Flaps Up/Down"),  category = _("Systems"), },
{pressed = 3019, up = 3020, cockpit_device_id = 22, value_pressed = 1, value_up = 0,  name = _("A-4 Sight Manual Ranging Control (Throttle Twist Grip) - CW/Decrease"),  category = _("A-4 Sight"), },
{down = 3003, cockpit_device_id = 13, value_down = 1,  name = _("Throttle - Stop Engine"),  category = _("Systems"), },
{down = 3005, cockpit_device_id = 26, value_down = 1,  name = _("AN/ARC-27 UHF Preset Channel Selector - CW/Increase"),  category = _("AN/ARC-27 UHF Radio"), },
{down = 3017, up = 3017, cockpit_device_id = 5, value_down = 1, value_up = 0,  name = _("Bomb-Rocket-Tank Jettison Button"),  category = _("Drop Tank Control Panel"), },
{combos = {{key = "JOY_BTN8"}, }, pressed = iCommandPlaneAirBrakeOn, up = iCommandPlaneAirBrakeOn, value_pressed = 1, value_up = 0,  name = _("Airbrake On"),  category = _("Systems"), },
{down = 3026, cockpit_device_id = 5, value_down = 1,  name = _("Gun Heater Switch"),  category = _("Center Pedestal"), },
{down = iCommandViewStatic,  name = _("F12 Static object view"),  category = _("View"), },
{down = iCommandViewSnapView5, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  5"),  category = _("View Cockpit"), },
{pressed = 3006, cockpit_device_id = 26, value_pressed = -0.075,  name = _("AN/ARC-27 UHF Audio Volume Knob - CCW/Down"),  category = _("AN/ARC-27 UHF Radio"), },
{pressed = iCommandViewPitCameraMoveForward, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Forward"),  category = _("View Cockpit"), },
{down = ICommandSwitchToCommonDialog,  name = _("Switch to main menu"),  category = _("Communications"), },
{pressed = iCommandViewCenter,  name = _("View Center"),  category = _("View"), },
{down = iCommandEnginesStop,  name = _("Auto Stop"),  category = _("Cheat"), },
{down = iCommandPlaneGearUp,  name = _("Landing Gear Up"),  category = _("Systems"), },
{pressed = iCommandViewUpRight, up = iCommandViewStop,  name = _("View up right"),  category = _("View Cockpit"), },
{down = 3003, cockpit_device_id = 100, value_down = 1,  name = _("Kneeboard current position mark point"),  category = _("Kneeboard"), },
{pressed = 3005, up = 3005, cockpit_device_id = 27, value_pressed = 1, value_up = 0,  name = _("AN/ARN-6 Loop Switch - Right"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandPlaneChangeLock, up = iCommandPlaneChangeLockUp,  name = _("A-4 Sight Radar Target Selector Button"),  category = _("A-4 Sight"), },
{down = iCommandViewSnapView4, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  4"),  category = _("View Cockpit"), },
{down = iCommandViewCameraDownRight, up = iCommandViewCameraCenter,  name = _("Glance down-right"),  category = _("View Cockpit"), },
{down = 3013, cockpit_device_id = 27, value_down = 1,  name = _("AN/ARN-6 Function Selector Switch - CW"),  category = _("AN/ARN-6 Radio Compass"), },
{combos = {{key = "JOY_BTN29"}, {key = "JOY_BTN30"}, }, down = 3003, up = 3002, cockpit_device_id = 13, value_down = 1, value_up = 1,  name = _("Throttle - Start/Stop"),  category = _("Systems"), },
{pressed = iCommandViewDownSlow, up = iCommandViewStopSlow,  name = _("View Down slow"),  category = _("View"), },
{pressed = iCommandViewDownRight, up = iCommandViewStop,  name = _("View down right"),  category = _("View Cockpit"), },
{down = iCommandViewBriefing,  name = _("View briefing on/off"),  category = _("General"), },
{down = iCommand_ExplorationStart,  name = _("Enable visual recon mode"),  category = _("View Cockpit"), },
{pressed = iCommandViewDownLeft, up = iCommandViewStop,  name = _("View down left"),  category = _("View Cockpit"), },
{down = 3014, cockpit_device_id = 27, value_down = 1,  name = _("AN/ARN-6 Frequency Band Switch - CW/Increase"),  category = _("AN/ARN-6 Radio Compass"), },
{down = 3034, cockpit_device_id = 5, value_down = -1,  name = _("Demolition Bomb Arming Switch - Down"),  category = _("Center Pedestal"), },
{down = 3008, cockpit_device_id = 29, value_down = 1,  name = _("AN/APX-6 IFF Mode 3 Switch"),  category = _("AN/APX-6 IFF Transponder"), },
{down = iCommandPlaneAirBrake,  name = _("Airbrake"),  category = _("Systems"), },
{down = iCommandViewAWACS,  name = _("F10 Theater map view"),  category = _("View"), },
{down = 3047, cockpit_device_id = 1, value_down = 1,  name = _("Generator Switch Cover"),  category = _("Right Forward Console"), },
{down = iCommandViewLock,  name = _("Lock View (cycle padlock)"),  category = _("View Padlock"), },
{pressed = 3018, up = 3020, cockpit_device_id = 22, value_pressed = 1, value_up = 0,  name = _("A-4 Sight Manual Ranging Control (Throttle Twist Grip) - CCW/Increase"),  category = _("A-4 Sight"), },
{pressed = iCommandViewDownRightSlow, up = iCommandViewStopSlow,  name = _("View Down Right slow"),  category = _("View"), },
{down = iCommandClockElapsedTimeReset,  name = _("Elapsed Time Clock Start/Stop/Reset"),  category = _("Systems"), },
{down = iCommandViewFree,  name = _("F11 Airport free camera"),  category = _("View"), },
{down = iCommandViewCameraReturn,  name = _("Return Camera"),  category = _("View Cockpit"), },
{down = iCommandAWACSHomeBearing,  name = _("Request AWACS Home Airbase"),  category = _("Communications"), },
{down = iCommandViewAngleDefault,  name = _("Zoom normal"),  category = _("View"), },
{down = iCommandViewGround,  name = _("F7 Ground unit view"),  category = _("View"), },
{down = iCommandViewSnapView6, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  6"),  category = _("View Cockpit"), },
{down = iCommandViewCameraDownSlow,  name = _("Camera snap view down"),  category = _("View Cockpit"), },
{pressed = 3021, cockpit_device_id = 22, value_pressed = -0.2,  name = _("Bomb-Target Wind Control Knob - CCW"),  category = _("Center Pedestal"), },
{down = iCommandViewTempCockpitOn, up = iCommandViewTempCockpitOff,  name = _("Cockpit panel view in"),  category = _("View Cockpit"), },
{down = 3006, cockpit_device_id = 17, value_down = 1,  name = _("Compass Light Switch"),  category = _("Right Forward Console"), },
{down = iCommandViewCameraUp, up = iCommandViewCameraCenter,  name = _("Glance up"),  category = _("View Cockpit"), },
{pressed = iCommandViewBack, up = iCommandViewBackStop,  name = _("Zoom out"),  category = _("View Cockpit"), },
{down = 3001, cockpit_device_id = 100, value_down = 1,  name = _("Kneeboard Next Page"),  category = _("Kneeboard"), },
{down = iCommandPlanePickleOn, up = iCommandPlanePickleOff,  name = _("Weapon Release"),  category = _("Stick Grip"), },
{down = iCommandViewAll,  name = _("View all mode"),  category = _("View Extended"), },
{down = iCommandChat,  name = _("Multiplayer chat - mode All"),  category = _("General"), },
{down = 3010, cockpit_device_id = 16, value_down = 1,  name = _("Pitot Heater Switch"),  category = _("Left Forward Console"), },
{combos = {{key = "JOY_BTN23"}, }, pressed = iCommandPlaneFlapsOn, up = iCommandPlaneFlapsOn, value_pressed = 1, value_up = 0,  name = _("Flaps Down"),  category = _("Systems"), },
{down = iCommandViewSnapView9, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  9"),  category = _("View Cockpit"), },
{down = iCommandViewMirage,  name = _("F12 Civil traffic view"),  category = _("View"), },
{pressed = iCommandViewUp, up = iCommandViewStop,  name = _("View up"),  category = _("View Cockpit"), },
{down = ICommandSwitchDialog,  name = _("Switch dialog"),  category = _("Communications"), },
{pressed = iCommandViewBackSlow, up = iCommandViewBackSlowStop,  name = _("Zoom out slow"),  category = _("View"), },
{pressed = iCommandThrottleIncrease, up = iCommandThrottleStop,  name = _("Thrust Smoothly Up"),  category = _("Flight Control"), },
{down = iCommandPlaneShowKneeboard, up = iCommandPlaneShowKneeboard, value_down = 1, value_up = -1,  name = _("Kneeboard glance view"),  category = _("Kneeboard"), },
{down = iCommandAllMissilePadlock,  name = _("All missiles padlock"),  category = _("View Padlock"), },
{down = iCommandViewSpeedUp,  name = _("F11 Camera moving forward"),  category = _("View"), },
{down = iCommandViewTransposeModeOn, up = iCommandViewTransposeModeOff,  name = _("Camera transpose mode (press and hold)"),  category = _("View Cockpit"), },
{down = iCommandViewRear,  name = _("F4 Look back view"),  category = _("View"), },
{down = iCommandPlaneRightStart, up = iCommandPlaneRightStop,  name = _("Aircraft Bank Right"),  category = _("Flight Control"), },
{down = 3002, cockpit_device_id = 13, value_down = 1,  name = _("Throttle - Start Engine"),  category = _("Systems"), },
{down = iCommandPlaneFonar,  name = _("Canopy Open/Close"),  category = _("Systems"), },
{down = 3012, cockpit_device_id = 25, value_down = 1,  name = _("Canopy Declutch Handle"),  category = _("Center Pedestal"), },
{down = iCommandPlaneGear,  name = _("Landing Gear Up/Down"),  category = _("Systems"), },
{down = 3006, cockpit_device_id = 18, value_down = -1,  name = _("Position and Fuselage Light Selector Switch - Down"),  category = _("Right Forward Console"), },
{down = 3006, cockpit_device_id = 18, value_down = 1,  name = _("Position and Fuselage Light Selector Switch - Up"),  category = _("Right Forward Console"), },
{down = iCommandViewSnapView8, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  8"),  category = _("View Cockpit"), },
{down = 3034, cockpit_device_id = 5, value_down = 1,  name = _("Demolition Bomb Arming Switch - Up"),  category = _("Center Pedestal"), },
{down = 3033, cockpit_device_id = 5, value_down = -1,  name = _("Demolition Bomb Sequence Selector Switch - CCW"),  category = _("Center Pedestal"), },
{down = 3033, cockpit_device_id = 5, value_down = 1,  name = _("Demolition Bomb Sequence Selector Switch - CW"),  category = _("Center Pedestal"), },
{down = iCommandViewCameraBaseReturn,  name = _("Return Camera Base"),  category = _("View Cockpit"), },
{down = 3030, cockpit_device_id = 5, value_down = 1,  name = _("Rocket Jettison Switch"),  category = _("Center Pedestal"), },
{pressed = iCommandViewPitCameraMoveRight, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Right"),  category = _("View Cockpit"), },
{pressed = iCommandViewExternalZoomIn, up = iCommandViewExternalZoomInStop,  name = _("Zoom external in"),  category = _("View"), },
{down = 3004, cockpit_device_id = 18, value_down = 1,  name = _("Exterior Lighting Dimmer Switch"),  category = _("Right Forward Console"), },
{down = 3032, cockpit_device_id = 5, value_down = 1,  name = _("Demolition Bomb Release Selector Switch"),  category = _("Center Pedestal"), },
{pressed = iCommandViewExternalZoomOut, up = iCommandViewExternalZoomOutStop,  name = _("Zoom external out"),  category = _("View"), },
{down = iCommandViewCameraLeftSlow,  name = _("Camera snap view left"),  category = _("View Cockpit"), },
{down = 3028, cockpit_device_id = 5, value_down = 1,  name = _("Rocket Release Selector Switch Cover"),  category = _("Center Pedestal"), },
{down = 3025, cockpit_device_id = 5, value_down = 1,  name = _("Gun-Missile Selector Switch - CCW"),  category = _("Center Pedestal"), },
{down = iCommandViewHUDOnlyOnOff,  name = _("F1 HUD only view switch"),  category = _("View"), },
{down = iCommandViewSnapView1, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  1"),  category = _("View Cockpit"), },
{pressed = 3023, cockpit_device_id = 22, value_pressed = -0.1,  name = _("Variable Sight Selector Unit - Rocket Depression Angle Selector - CCW"),  category = _("Center Pedestal"), },
{down = iCommandViewCameraRight, up = iCommandViewCameraCenter,  name = _("Glance right"),  category = _("View Cockpit"), },
{down = iCommandViewCameraRightSlow,  name = _("Camera snap view right"),  category = _("View Cockpit"), },
{down = iCommandActivePauseOnOff,  name = _("Active Pause"),  category = _("Cheat"), },
{combos = {{key = "JOY_BTN22"}, }, pressed = iCommandPlaneFlapsOff, up = iCommandPlaneFlapsOff, value_pressed = 1, value_up = 0,  name = _("Flaps Up"),  category = _("Systems"), },
{pressed = 3023, cockpit_device_id = 22, value_pressed = 0.1,  name = _("Variable Sight Selector Unit - Rocket Depression Angle Selector - CW"),  category = _("Center Pedestal"), },
{down = iCommandViewCameraLeft, up = iCommandViewCameraCenter,  name = _("Glance left"),  category = _("View Cockpit"), },
{down = iCommandViewUnlock,  name = _("Unlock view (stop padlock)"),  category = _("View Padlock"), },
{down = iCommandPlaneFormation,  name = _("Toggle Formation"),  category = _("Communications"), },
{down = iCommandViewSaveAngles,  name = _("Save Cockpit Angles"),  category = _("View Cockpit"), },
{down = iCommandViewCameraCenter,  name = _("Center Camera View"),  category = _("View Cockpit"), },
{pressed = 3002, cockpit_device_id = 21, value_pressed = -1,  name = _("A-4 Sight Radar Range Sweep Rheostat - CCW/Decrease"),  category = _("A-4 Sight"), },
{down = 3022, cockpit_device_id = 22, value_down = 1,  name = _("Variable Sight Selector Unit - Target Speed Switch"),  category = _("Center Pedestal"), },
{pressed = iCommandViewPitCameraMoveLeft, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Left"),  category = _("View Cockpit"), },
{pressed = 3021, cockpit_device_id = 22, value_pressed = 0.2,  name = _("Bomb-Target Wind Control Knob - CW"),  category = _("Center Pedestal"), },
{down = iCommandPlaneWingtipSmokeOnOff,  name = _("Smoke"),  category = _("Systems"), },
{pressed = iCommandPlaneTrimUp, up = iCommandPlaneTrimStop,  name = _("Trim Up"),  category = _("Flight Control"), },
{pressed = 3036, cockpit_device_id = 5, value_pressed = -1,  name = _("A-4 Sight Bombing Altimeter Index Altitude Handle - CCW/Decrease"),  category = _("A-4 Sight"), },
{pressed = iCommandPlaneTrimLeft, up = iCommandPlaneTrimStop,  name = _("Trim Left"),  category = _("Flight Control"), },
{pressed = 3035, cockpit_device_id = 5, value_pressed = -1,  name = _("A-4 Sight Bombing Altimeter Target Altitude Knob - CCW/Decrease"),  category = _("A-4 Sight"), },
{pressed = 3005, cockpit_device_id = 22, value_pressed = 0.2,  name = _("A-4 Sight Reticle Dimmer Control - CW/BRIGHT"),  category = _("A-4 Sight"), },
{down = iCommandViewTower,  name = _("F3 Fly-By view"),  category = _("View"), },
{down = iCommandPlaneFire, up = iCommandPlaneFireOff,  name = _("Gun Fire"),  category = _("Stick Grip"), },
{down = iCommandViewRightMirrorOn, up = iCommandViewRightMirrorOff,  name = _("Mirror Right On"),  category = _("View Cockpit"), },
{down = 3007, cockpit_device_id = 26, value_down = 1,  name = _("AN/ARC-27 UHF Power Switch - CW"),  category = _("AN/ARC-27 UHF Radio"), },
{pressed = 3009, cockpit_device_id = 17, value_pressed = 0.5,  name = _("Console and Panel Light Rheostat - CW/Increase"),  category = _("Interior Light Control Panel"), },
{pressed = 3008, cockpit_device_id = 17, value_pressed = -0.5,  name = _("Instrument Panel Auxiliary Light Rheostat - CCW/Decrease"),  category = _("Interior Light Control Panel"), },
{down = iCommandPlaneDownStart, up = iCommandPlaneDownStop,  name = _("Aircraft Up"),  category = _("Flight Control"), },
{pressed = 3008, cockpit_device_id = 17, value_pressed = 0.5,  name = _("Instrument Panel Auxiliary Light Rheostat - CW/Increase"),  category = _("Interior Light Control Panel"), },
{down = iCommandViewSnapView0, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  0"),  category = _("View Cockpit"), },
{down = iCommandPlaneJettisonWeapons, up = iCommandPlaneJettisonWeaponsUp,  name = _("Weapons Jettison"),  category = _("Systems"), },
{pressed = 3007, cockpit_device_id = 17, value_pressed = -0.5,  name = _("Instrument Panel Primary Light Rheostat - CCW/Decrease"),  category = _("Interior Light Control Panel"), },
{pressed = 3007, cockpit_device_id = 17, value_pressed = 0.5,  name = _("Instrument Panel Primary Light Rheostat - CW/Increase"),  category = _("Interior Light Control Panel"), },
{pressed = iCommandPlaneDecreaseBase_Distance, up = iCommandPlaneStopBase_Distance,  name = _("A-4 Sight Wing Span Adjustment Knob - Wing Span Decrease"),  category = _("A-4 Sight"), },
{down = 3005, cockpit_device_id = 26, value_down = -1,  name = _("AN/ARC-27 UHF Preset Channel Selector - CCW/Decrease"),  category = _("AN/ARC-27 UHF Radio"), },
{down = iCommandViewObjectsAll,  name = _("Objects all excluded - include"),  category = _("View Extended"), },
{down = iCommandViewNormalKeyboard,  name = _("Keyboard Rate Normal"),  category = _("View"), },
{down = iCommandViewTowerJump,  name = _("F3 Fly-By jump view"),  category = _("View"), },
{pressed = iCommandViewForwardSlow, up = iCommandViewForwardSlowStop,  name = _("Zoom in slow"),  category = _("View"), },
{down = iCommandPlane_EngageGroundTargets,  name = _("Flight - Attack ground targets"),  category = _("Communications"), },
{down = iCommandRecoverHuman,  name = _("Get new plane - respawn"),  category = _("General"), },
{down = iCommandCockpitClickModeOnOff,  name = _("Mouse cursor cockpit mode"),  category = _("General"), },
{down = iCommandScreenShot,  name = _("Screenshot"),  category = _("General"), },
{down = iCommandPlaneJoinUp,  name = _("Join Up Formation"),  category = _("Communications"), },
{down = 3003, up = 3003, cockpit_device_id = 1, value_down = 1, value_up = 0,  name = _("Stop-Starter Button"),  category = _("Right Forward Console"), },
{down = 3006, cockpit_device_id = 3, value_down = -1,  name = _("Drop Tank Selector Switch - CCW"),  category = _("Drop Tank Control Panel"), },
{down = iCommandViewCameraUpRight, up = iCommandViewCameraCenter,  name = _("Glance up-right"),  category = _("View Cockpit"), },
{down = iCommandViewFreeJump,  name = _("F11 Jump to free camera"),  category = _("View"), },
{down = 3007, cockpit_device_id = 3, value_down = 1,  name = _("Fuel Densitometer Selection Switch Cover"),  category = _("Right Forward Console"), },
{down = 3004, cockpit_device_id = 4, value_down = 1,  name = _("Emergency (In-air) Ignition Switch Cover"),  category = _("Right Forward Console"), },
{pressed = iCommandPlaneTrimRightRudder, up = iCommandPlaneTrimStop,  name = _("Trim Right Rudder"),  category = _("Flight Control"), },
{down = iCommandPlaneWheelBrakeLeftOn, up = iCommandPlaneWheelBrakeLeftOff,  name = _("Wheel Brake Left On/Off"),  category = _("Systems"), },
{combos = {{key = "JOY_BTN21"}, }, down = 3004, up = 3004, cockpit_device_id = 3, value_down = 1, value_up = 0,  name = _("Drop Tank Jettison Button"),  category = _("Drop Tank Control Panel"), },
{pressed = iCommandViewLeftSlow, up = iCommandViewStopSlow,  name = _("View Left slow"),  category = _("View"), },
{down = 3015, cockpit_device_id = 27, value_down = -1,  name = _("AN/ARN-6 Scale Light Switch - Down"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandViewPitHeadOnOff,  name = _("F1 Head shift movement on / off"),  category = _("View"), },
{down = iCommandViewCameraDownLeft, up = iCommandViewCameraCenter,  name = _("Glance down-left"),  category = _("View Cockpit"), },
{pressed = iCommandPlaneTrimLeftRudder, up = iCommandPlaneTrimStop,  name = _("Trim Left Rudder"),  category = _("Flight Control"), },
{down = iCommandViewLocomotivesToggle,  name = _("F12 Trains/cars toggle"),  category = _("View"), },
{down = iCommandNaturalViewCockpitIn,  name = _("F1 Natural head movement view"),  category = _("View"), },
{down = iCommandViewPlus,  name = _("Toggle tracking launched weapon"),  category = _("View Extended"), },
{down = iCommandViewSnapView3, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  3"),  category = _("View Cockpit"), },
{down = 3006, cockpit_device_id = 3, value_down = 1,  name = _("Drop Tank Selector Switch - CW"),  category = _("Drop Tank Control Panel"), },
{combos = {{key = "JOY_BTN5"}, }, down = 3004, up = 3004, cockpit_device_id = 26, value_down = 1, value_up = 0,  name = _("Microphone Button"),  category = _("Communications"), },
{down = iCommandPlaneAUTIncreaseRegime,  name = _("Thrust Step Up"),  category = _("Flight Control"), },
{down = iCommandPlaneDoAndHome,  name = _("Flight - Complete mission and RTB"),  category = _("Communications"), },
{down = iCommandPlaneAttackMyTarget,  name = _("Attack My Target"),  category = _("Communications"), },
{down = iCommandFlightClockReset,  name = _("Flight Clock Start/Stop/Reset"),  category = _("Systems"), },
{down = iCommandViewExternalZoomDefault,  name = _("Zoom external normal"),  category = _("View"), },
{down = iCommandViewCameraUpLeft, up = iCommandViewCameraCenter,  name = _("Glance up-left"),  category = _("View Cockpit"), },
{down = iCommandAccelerate,  name = _("Time accelerate"),  category = _("General"), },
{down = iCommandViewSwitchForward,  name = _("Objects switching direction forward "),  category = _("View Extended"), },
{pressed = iCommandViewRightSlow, up = iCommandViewStopSlow,  name = _("View Right slow"),  category = _("View"), },
{down = 3004, up = 3004, cockpit_device_id = 29, value_down = 1, value_up = -1,  name = _("AN/APX-6 IFF Destruct Switch"),  category = _("AN/APX-6 IFF Transponder"), },
{pressed = 3005, up = 3005, cockpit_device_id = 27, value_pressed = -1, value_up = 0,  name = _("AN/ARN-6 Loop Switch - Left"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandQuit,  name = _("End mission"),  category = _("General"), },
{down = 3009, cockpit_device_id = 29, value_down = 1,  name = _("AN/APX-6 IFF Destruct Switch Cover"),  category = _("AN/APX-6 IFF Transponder"), },
{down = 3050, cockpit_device_id = 1, value_down = 1,  name = _("Battery-Starter Switch - Up"),  category = _("Right Forward Console"), },
{down = 3050, up = 3050, cockpit_device_id = 1, value_down = -1, value_up = 0,  name = _("Battery-Starter Switch - Down"),  category = _("Right Forward Console"), },
{down = iCommandViewSlowDown,  name = _("F11 Camera moving backward"),  category = _("View"), },
{down = 3006, cockpit_device_id = 29, value_down = 1,  name = _("AN/APX-6 IFF Master Switch - CW"),  category = _("AN/APX-6 IFF Transponder"), },
{pressed = iCommandThrottleDecrease, up = iCommandThrottleStop,  name = _("Thrust Smoothly Down"),  category = _("Flight Control"), },
{down = iCommandViewCameraJiggle,  name = _("Camera jiggle toggle"),  category = _("View Extended"), },
{down = 3011, up = 3011, cockpit_device_id = 25, value_down = 1, value_up = 0,  name = _("Manual Canopy Jettison"),  category = _("Systems"), },
{down = iCommandPlaneCoverMySix,  name = _("Cover Me"),  category = _("Communications"), },
{down = iCommandEnginesStart,  name = _("Auto Start"),  category = _("Cheat"), },
{pressed = 3006, cockpit_device_id = 26, value_pressed = 0.075,  name = _("AN/ARC-27 UHF Audio Volume Knob - CW/Up"),  category = _("AN/ARC-27 UHF Radio"), },
{pressed = iCommandViewPitCameraMoveUp, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Up"),  category = _("View Cockpit"), },
{down = iCommandDecelerate,  name = _("Time decelerate"),  category = _("General"), },
{down = 3008, cockpit_device_id = 3, value_down = 1,  name = _("Fuel Densitometer Selection Switch"),  category = _("Right Forward Console"), },
{pressed = 3011, cockpit_device_id = 27, value_pressed = -0.3,  name = _("AN/ARN-6 Audio Volume Control - Down"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandViewCockpit,  name = _("F1 Cockpit view"),  category = _("View"), },
{pressed = iCommandPlaneTrimDown, up = iCommandPlaneTrimStop,  name = _("Trim Down"),  category = _("Flight Control"), },
{pressed = iCommandViewDown, up = iCommandViewStop,  name = _("View down"),  category = _("View Cockpit"), },
{down = iCommandPlaneGearDown,  name = _("Landing Gear Down"),  category = _("Systems"), },
{down = iCommandViewFightGround,  name = _("F5 Ground hostile view"),  category = _("View"), },
{down = iCommandViewWeaponAndTarget,  name = _("F6 Weapon to target view"),  category = _("View"), },
{down = iCommandPlane_HOTAS_NoseWheelSteeringButton, up = iCommandPlane_HOTAS_NoseWheelSteeringButtonOff,  name = _("Nosewheel Steering Button"),  category = _("Stick Grip"), },
{down = 3051, cockpit_device_id = 1, value_down = 1,  name = _("Instrument Power Switch"),  category = _("Center Pedestal"), },
{down = iCommandViewTargetType,  name = _("F8 Player targets/All targets filter"),  category = _("View"), },
{down = iCommandViewFromTo,  name = _("F2 Toggle camera position"),  category = _("View"), },
{down = iCommandNoAcceleration,  name = _("Time normal"),  category = _("General"), },
{down = iCommandViewCameraDownLeftSlow,  name = _("Camera snap view down-left"),  category = _("View Cockpit"), },
{down = iCommandViewCoordinatesInLinearUnits,  name = _("Info bar coordinate units toogle"),  category = _("General"), },
{pressed = 3010, cockpit_device_id = 27, value_pressed = -1,  name = _("AN/ARN-6 Tuning Crank - CCW/Decrease Frequency"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandViewCameraUpLeftSlow,  name = _("Camera snap view up-left"),  category = _("View Cockpit"), },
{down = iCommandMissionResourcesManagement,  name = _("Rearming and Refueling Window"),  category = _("General"), },
{down = iCommandPlaneLeftRudderStart, up = iCommandPlaneLeftRudderStop,  name = _("Aircraft Rudder Left"),  category = _("Flight Control"), },
{down = iCommandPlaneLeftStart, up = iCommandPlaneLeftStop,  name = _("Aircraft Bank Left"),  category = _("Flight Control"), },
{pressed = 3010, cockpit_device_id = 27, value_pressed = 1,  name = _("AN/ARN-6 Tuning Crank - CW/Increase Frequency"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandMarkerStateShip,  name = _("Vehicle & Ship Labels"),  category = _("Labels"), },
{down = iCommandMarkerStateRocket,  name = _("Missile Labels"),  category = _("Labels"), },
{down = iCommandPlaneWheelBrakeRightOn, up = iCommandPlaneWheelBrakeRightOff,  name = _("Wheel Brake Right On/Off"),  category = _("Systems"), },
{down = iCommandThreatMissilePadlock,  name = _("Threat missile padlock"),  category = _("View Padlock"), },
{down = iCommandPlaneEject,  name = _("Eject (3 times)"),  category = _("Systems"), },
{down = iCommandPlaneAUTDecreaseRegime,  name = _("Thrust Step Down"),  category = _("Flight Control"), },
{down = iCommandViewNormalMouse,  name = _("Mouse Rate Normal"),  category = _("View"), },
{down = iCommandViewObjectIgnore,  name = _("Object exclude "),  category = _("View Extended"), },
{down = iCommandViewSwitchReverse,  name = _("Objects switching direction reverse "),  category = _("View Extended"), },
{down = iCommandViewFriends,  name = _("View friends mode"),  category = _("View Extended"), },
{down = iCommandViewKeepTerrain,  name = _("Keep terrain camera altitude"),  category = _("View Extended"), },
{pressed = 3009, cockpit_device_id = 27, value_pressed = 1,  name = _("AN/ARN-6 East/West Variation Knob - CW/West"),  category = _("AN/ARN-6 Radio Compass"), },
{down = iCommandViewSnapView7, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  7"),  category = _("View Cockpit"), },
{down = iCommandViewPanToggle,  name = _("Camera pan mode toggle"),  category = _("View Cockpit"), },
{down = iCommandViewFastMouse,  name = _("Mouse Rate Fast"),  category = _("View"), },
{down = iCommandViewSnapView2, up = iCommandViewSnapViewStop,  name = _("Custom Snap View  2"),  category = _("View Cockpit"), },
{down = 3027, cockpit_device_id = 5, value_down = -1,  name = _("Rocket Release Selector Switch - Down"),  category = _("Center Pedestal"), },
{down = 3049, cockpit_device_id = 1, value_down = 1,  name = _("Engine Master Switch"),  category = _("Right Forward Console"), },
{down = 3029, cockpit_device_id = 5, value_down = -1,  name = _("Variable Sight Selector Unit - Sight Function Selector Lever - CW"),  category = _("Center Pedestal"), },
{down = iCommandViewCameraDownRightSlow,  name = _("Camera snap view down-right"),  category = _("View Cockpit"), },
{down = iCommandViewLocal,  name = _("F2 Toggle local camera control"),  category = _("View"), },
{down = iCommandInfoOnOff,  name = _("Info bar view toggle"),  category = _("General"), },
{down = iCommandViewCameraUpSlow,  name = _("Camera snap view up"),  category = _("View Cockpit"), },
{pressed = iCommandViewForward, up = iCommandViewForwardStop,  name = _("Zoom in"),  category = _("View Cockpit"), },
{down = iCommandViewAWACSJump,  name = _("F10 Jump to theater map view over current point"),  category = _("View"), },
{down = iCommandPlane_EngageAirDefenses,  name = _("Flight - Attack air defenses"),  category = _("Communications"), },
{down = iCommandScoresWindowToggle,  name = _("Score window"),  category = _("General"), },
{down = iCommandViewSlowKeyboard,  name = _("Keyboard Rate Slow"),  category = _("View"), },
{pressed = iCommandViewPitCameraMoveBack, up = iCommandViewPitCameraMoveStop,  name = _("Cockpit Camera Move Back"),  category = _("View Cockpit"), },
{pressed = iCommandViewUpLeft, up = iCommandViewStop,  name = _("View up left"),  category = _("View Cockpit"), },
{down = iCommandPlaneDoAndBack,  name = _("Flight - Complete mission and rejoin"),  category = _("Communications"), },
{down = iCommandViewTempCockpitToggle,  name = _("Cockpit panel view toggle"),  category = _("View Cockpit"), },
{down = iCommandGraphicsFrameRate,  name = _("Frame rate counter - Service info"),  category = _("General"), },
{down = iCommandViewSlowMouse,  name = _("Mouse Rate Slow"),  category = _("View"), },
{down = iCommandPlaneJettisonFuelTanks, up = iCommandPlaneJettisonFuelTanksUp,  name = _("Jettison Fuel Tanks"),  category = _("Systems"), },
{combos = {{key = "JOY_BTN3"}, }, down = iCommandToggleCommandMenu,  name = _("Communication menu"),  category = _("Communications"), },
{down = iCommandViewLndgOfficer,  name = _("F9 Landing signal officer view"),  category = _("View"), },
{down = iCommandViewWeapons,  name = _("F6 Released weapon view"),  category = _("View"), },
{down = iCommandViewFight,  name = _("F5 nearest AC view"),  category = _("View"), },
{down = iCommandPlaneJump,  name = _("Jump into selected aircraft"),  category = _("General"), },
{down = 3001, up = 3001, cockpit_device_id = 4, value_down = 1, value_up = -1,  name = _("Emergency (In-air) Ignition Switch"),  category = _("Right Forward Console"), },
{down = iCommandViewChase,  name = _("F4 Chase view"),  category = _("View"), },
{down = iCommandSoundOnOff,  name = _("Sound On/Off"),  category = _("General"), },
{pressed = iCommandViewUpRightSlow, up = iCommandViewStopSlow,  name = _("View Up Right slow"),  category = _("View"), },
},
axisCommands = {
{action = iCommandPlaneViewVertical,  name = _("Camera Vertical View"), },
{action = iCommandViewHorizontalAbs,  name = _("Absolute Camera Horizontal View"), },
{combos = {{key = "JOY_SLIDER1", filter = {curvature = {0}, deadzone = 0, invert = true, saturationX = 1, saturationY = 1, slider = false},}, }, action = iCommandPlaneSelecterVerticalAbs,  name = _("Manual Range"), },
{combos = {{key = "JOY_Z"}, }, action = iCommandPlaneThrustCommon,  name = _("Thrust"), },
{action = iCommandRightWheelBrake,  name = _("Wheel Brake Right"), },
{action = iCommandPlaneRudder,  name = _("Rudder"), },
{action = iCommandPlaneRoll,  name = _("Roll"), },
{action = iCommandPlaneViewHorizontal,  name = _("Camera Horizontal View"), },
{action = iCommandLeftWheelBrake,  name = _("Wheel Brake Left"), },
{action = iCommandPlanePitch,  name = _("Pitch"), },
{action = iCommandViewRollAbs,  name = _("Absolute Roll Shift Camera View"), },
{action = iCommandViewLongitudeTransAbs,  name = _("Absolute Longitude Shift Camera View"), },
{action = iCommandViewZoomAbs,  name = _("Zoom View"), },
{action = iCommandViewVerticalAbs,  name = _("Absolute Camera Vertical View"), },
{action = iCommandPlaneBase_DistanceAbs,  name = _("Wing Span"), },
{action = iCommandWheelBrake,  name = _("Wheel Brake"), },
{action = iCommandViewVertTransAbs,  name = _("Absolute Vertical Shift Camera View"), },
{action = iCommandViewHorTransAbs,  name = _("Absolute Horizontal Shift Camera View"), },
{action = iCommandPlaneZoomView,  name = _("Camera Zoom View"), },
},
}